# Generated by Django 5.2.13 on 2026-05-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_unique_non_empty_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["full_name"],
                "permissions": [("manage_user_roles", "Can manage users and roles")],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
