# Generated by Django 5.1.11 on 2026-06-30 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="delete_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
