# Generated by Django 5.2.13 on 2026-09-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_delete_reason_customuser_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
