# Generated by Django 5.2.13 on 2026-06-02 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpGuide",
            fields=[
                (
                    "help_guide_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "screen_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("route_path", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("all_users", "All users"),
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                            ("employee", "Employee"),
                            ("support", "Support"),
                            ("provider", "Provider"),
                            ("platform_super_admin", "Platform super admin"),
                            ("platform_support", "Platform support"),
                            ("partner_owner", "Partner owner"),
                            ("partner_admin", "Partner admin"),
                            ("branch_manager", "Branch manager"),
                            ("partner_employee", "Partner employee"),
                            ("provider_admin", "Provider admin"),
                            ("provider_employee", "Provider employee"),
                            ("finance", "Finance"),
                            ("auditor", "Auditor"),
                        ],
                        db_index=True,
                        default="all_users",
                        max_length=40,
                    ),
                ),
                (
                    "permission_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "workflow_status",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("title", models.CharField(max_length=255)),
                ("short_description", models.TextField(blank=True)),
                ("purpose", models.TextField(blank=True)),
                ("before_you_start", models.TextField(blank=True)),
                ("step_by_step_guide", models.TextField(blank=True)),
                ("expected_result", models.TextField(blank=True)),
                ("common_errors", models.TextField(blank=True)),
                ("related_screen", models.CharField(blank=True, max_length=100)),
                ("related_permission", models.CharField(blank=True, max_length=120)),
                ("search_keywords", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_help_guides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_help_guides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "title", "help_guide_id"],
                "permissions": [
                    ("manage_help_guides", "Can manage in-app help guide content")
                ],
                "indexes": [
                    models.Index(
                        fields=["screen_key", "role", "is_active"],
                        name="help_guides_screen__164678_idx",
                    ),
                    models.Index(
                        fields=["screen_key", "workflow_status", "is_active"],
                        name="help_guides_screen__95d047_idx",
                    ),
                    models.Index(
                        fields=["role", "permission_key", "is_active"],
                        name="help_guides_role_064346_idx",
                    ),
                ],
            },
        ),
    ]
