from django.db import migrations

from help_guides.screen_registry import HELP_SCREEN_MAP


SEED_GUIDES = [
    {
        "screen_key": "",
        "route_path": "",
        "role": "customer",
        "title": "الدليل العام للعميل",
        "short_description": "مرجع سريع لفهم مسار الطلبات داخل بوابة العميل.",
        "purpose": "يساعدك هذا الدليل على معرفة مكان إنشاء الطلب، متابعة الحالة، والرد على طلبات النواقص.",
        "before_you_start": "تأكد من اكتمال بيانات الحساب ورقم الهاتف، واحتفظ بالمستندات الأساسية بصيغة واضحة.",
        "step_by_step_guide": "1. افتح لوحة العميل لمراجعة حالة الطلبات.\n2. استخدم شاشة الطلبات للوصول إلى أي طلب نشط.\n3. راقب الإشعارات وطلبات المستندات الناقصة أولاً بأول.\n4. افتح تفاصيل الطلب قبل رفع أي ملف إضافي.",
        "expected_result": "تستطيع متابعة الطلب من البداية حتى استلام النتيجة النهائية بدون مغادرة البوابة.",
        "common_errors": "رفع ملفات غير واضحة.\nتجاهل حالة الطلب قبل الرد.\nاستخدام مستند قديم بدل النسخة المطلوبة.",
        "related_screen": "customer_orders",
        "related_permission": "",
        "search_keywords": "عميل طلبات متابعة رفع مستندات",
        "display_order": 0,
    },
    {
        "screen_key": "",
        "route_path": "",
        "role": "employee",
        "title": "الدليل العام للموظف",
        "short_description": "مرجع تشغيلي لمراجعة الطلبات والتحقق من الوثائق.",
        "purpose": "يوضح التسلسل الآمن للعمل على الطلبات من المراجعة وحتى الإسناد أو الإكمال.",
        "before_you_start": "راجع فقط الطلبات المخصصة لك أو الظاهرة في قائمة المراجعة، واستخدم الإجراءات النظامية بدل التعديل المباشر.",
        "step_by_step_guide": "1. ابدأ من قائمة المراجعة أو لوحة الموظف.\n2. تحقق من الوثائق المطلوبة لكل خدمة.\n3. اطلب النواقص عند الحاجة مع ملاحظة واضحة.\n4. لا تسند الطلب إلى مزود قبل اكتمال التحقق.",
        "expected_result": "تُحافظ على انتقالات الحالة الصحيحة وتترك أثراً واضحاً لكل قرار داخل النظام.",
        "common_errors": "إسناد الطلب قبل اعتماد الوثائق.\nكتابة ملاحظة عامة لا توضح المطلوب.\nتنفيذ إجراء غير متاح في الحالة الحالية.",
        "related_screen": "employee_review_queue",
        "related_permission": "orders.review_order",
        "search_keywords": "موظف مراجعة طلبات تحقق وثائق",
        "display_order": 0,
    },
    {
        "screen_key": "",
        "route_path": "",
        "role": "support",
        "title": "الدليل العام للدعم",
        "short_description": "مرجع لمتابعة الطلبات الخدمية ومساعدة الفرق على ضبط التصنيفات والعلاقات.",
        "purpose": "يساعد فريق الدعم على المتابعة السريعة للطلبات المفتوحة وتنظيم الخدمات المرتبطة بها.",
        "before_you_start": "تحقق من الشاشة الحالية وصلاحياتك قبل تعديل أي تصنيف أو علاقة خدمة.",
        "step_by_step_guide": "1. استخدم قائمة المراجعة للبحث عن الطلب أو العميل.\n2. تابع طلبات الخدمات غير الموجودة عند ورودها.\n3. حدّث التصنيفات أو العلاقات فقط عندما تكون الصياغة والربط واضحين.\n4. دوّن أي ملاحظة تشغيلية للفريق عند الحاجة.",
        "expected_result": "يصل فريق الدعم إلى معلومات الطلب والخدمة بسرعة مع بقاء التصنيفات والعلاقات منظمة.",
        "common_errors": "اقتراح خدمة غير مرتبطة فعلياً.\nتعديل علاقة خدمة بدون مراجعة أثرها.\nترك طلب خدمة جديد بدون متابعة.",
        "related_screen": "employee_missing_service_requests",
        "related_permission": "",
        "search_keywords": "دعم خدمة علاقات تصنيفات طلبات",
        "display_order": 0,
    },
    {
        "screen_key": "",
        "route_path": "",
        "role": "provider",
        "title": "الدليل العام للمزود",
        "short_description": "مرجع سريع لمعالجة الطلبات المعيّنة ورفع النتيجة النهائية.",
        "purpose": "يوجه المزود للعمل على الطلبات المرسلة إليه دون تخطي خطوات التنفيذ المعتمدة.",
        "before_you_start": "افتح الطلب المعيّن لك فقط، وراجع المرفقات والملاحظات قبل تغيير الحالة أو رفع مستند نهائي.",
        "step_by_step_guide": "1. راجع الطلبات المعيّنة من شاشة الطلبات.\n2. افتح تفاصيل الطلب لتأكيد المستندات والملاحظات.\n3. حدّث الحالة حسب التقدم الفعلي.\n4. ارفع المستند النهائي فقط بعد اكتمال العمل.",
        "expected_result": "يتم استلام النتيجة النهائية داخل النظام مع بقاء سجل التنفيذ واضحاً للفريق الداخلي.",
        "common_errors": "رفع مستند نهائي قبل اكتمال المعالجة.\nإهمال قراءة الملاحظات الداخلية الظاهرة للمزود.\nترك الطلب في حالة قديمة بعد انتهاء العمل.",
        "related_screen": "provider_orders",
        "related_permission": "",
        "search_keywords": "مزود تنفيذ رفع نهائي طلبات",
        "display_order": 0,
    },
    {
        "screen_key": "",
        "route_path": "",
        "role": "admin",
        "title": "الدليل العام للإدارة",
        "short_description": "مرجع سريع لإدارة المستخدمين والخدمات والشاشات الإدارية.",
        "purpose": "يوضح أين تُدار كل مجموعة إعدادات حتى لا تتكرر نفس العملية في أكثر من شاشة.",
        "before_you_start": "راجع الشاشة التخصصية المناسبة قبل أي تعديل، وتجنب تغيير البيانات من شاشة غير مخصصة لها.",
        "step_by_step_guide": "1. استخدم لوحة الإدارة للوصول إلى القسم المطلوب.\n2. افتح شاشة الإدارة المتخصصة للخدمات أو المستخدمين أو المحتوى العام.\n3. عدّل البيانات المطلوبة فقط ثم راجع الأثر على الفرق الأخرى.\n4. استخدم شاشة دليل المستخدم لإدارة محتوى المساعدة الداخلي.",
        "expected_result": "تُدار الإعدادات من أماكنها الصحيحة مع تقليل الأخطاء الناتجة عن تكرار الإدارة.",
        "common_errors": "تعديل بيانات خدمة من شاشة لا تخصها.\nتعطيل مستخدم دون مراجعة دوره.\nتحديث محتوى عام بدون معاينة أثره.",
        "related_screen": "admin_dashboard",
        "related_permission": "help_guides.manage_help_guides",
        "search_keywords": "إدارة خدمات مستخدمين محتوى دليل",
        "display_order": 0,
    },
    {
        "screen_key": "customer_dashboard",
        "route_path": HELP_SCREEN_MAP["customer_dashboard"]["route_path"],
        "role": "customer",
        "title": "لوحة العميل",
        "short_description": "نقطة البداية لمتابعة النشاط الحالي والتنقل السريع إلى طلباتك.",
        "purpose": "تعرض لك ملخص الطلبات والحالات التي تحتاج إلى متابعة مباشرة.",
        "before_you_start": "افتح إشعاراتك أولاً إذا كان لديك طلب بانتظار مستندات أو تحديث جديد.",
        "step_by_step_guide": "1. راجع البطاقات المختصرة لمعرفة عدد الطلبات النشطة.\n2. انتقل إلى شاشة طلباتي لعرض جميع الطلبات.\n3. افتح إنشاء طلب جديد عند الحاجة إلى خدمة جديدة.",
        "expected_result": "تتعرف بسرعة على ما يحتاج إلى متابعة دون البحث في أكثر من شاشة.",
        "common_errors": "الاعتماد على الملخص فقط دون فتح تفاصيل الطلب.\nتجاهل التنبيهات المتعلقة بالنواقص.",
        "related_screen": "customer_orders",
        "related_permission": "",
        "search_keywords": "لوحة العميل ملخص الطلبات",
        "display_order": 10,
    },
    {
        "screen_key": "customer_create_order",
        "route_path": HELP_SCREEN_MAP["customer_create_order"]["route_path"],
        "role": "customer",
        "title": "إنشاء طلب جديد",
        "short_description": "اتبع هذه الخطوات لإرسال طلب مكتمل من أول مرة.",
        "purpose": "يقلل هذا الدليل من إعادة الطلب بسبب معلومات ناقصة أو مستندات غير مناسبة.",
        "before_you_start": "جهّز الخدمة المطلوبة، المدينة، والملاحظات الأساسية قبل الإرسال.",
        "step_by_step_guide": "1. اختر الخدمة الصحيحة من القائمة.\n2. أكمل الحقول المطلوبة بدقة.\n3. راجع المستندات المطلوبة للخدمة إن ظهرت.\n4. أرسل الطلب ثم افتح تفاصيله للتأكد من حالته الأولى.",
        "expected_result": "يُنشأ الطلب برقم واضح ويبدأ مسار المراجعة دون نقص في البيانات الأساسية.",
        "common_errors": "اختيار خدمة غير مطابقة للمطلوب.\nإرسال بيانات ناقصة في الحقول الإلزامية.",
        "related_screen": "customer_order_details",
        "related_permission": "",
        "search_keywords": "إنشاء طلب خدمة جديد",
        "display_order": 20,
    },
    {
        "screen_key": "customer_orders",
        "route_path": HELP_SCREEN_MAP["customer_orders"]["route_path"],
        "role": "customer",
        "title": "متابعة الطلبات",
        "short_description": "استخدم هذه الشاشة للبحث عن أي طلب وفتح تفاصيله.",
        "purpose": "تساعدك الشاشة على متابعة الحالة الحالية والوصول السريع إلى المستندات أو الخطوات المطلوبة.",
        "before_you_start": "يمكنك البحث برقم الطلب أو اسم الخدمة لتقليل الوقت.",
        "step_by_step_guide": "1. استخدم البحث للوصول إلى الطلب المطلوب.\n2. راجع حالة الطلب وتاريخ التسليم المتوقع.\n3. افتح تفاصيل الطلب إذا ظهرت حالة تحتاج إلى إجراء منك.",
        "expected_result": "تعرف الطلب الذي يحتاج إلى متابعة وما إذا كان مكتملًا أو بانتظار رد منك.",
        "common_errors": "عدم فتح تفاصيل الطلب عند ظهور حالة انتظار العميل.\nالخلط بين أكثر من طلب متشابه.",
        "related_screen": "customer_order_details",
        "related_permission": "",
        "search_keywords": "طلباتي متابعة حالة بحث",
        "display_order": 30,
    },
    {
        "screen_key": "customer_order_details",
        "route_path": HELP_SCREEN_MAP["customer_order_details"]["route_path"],
        "role": "customer",
        "title": "تفاصيل الطلب للعميل",
        "short_description": "راجع الحالة، المستندات، والملاحظات من شاشة واحدة.",
        "purpose": "تمكنك هذه الشاشة من فهم وضع الطلب الحالي ومعرفة ما إذا كان هناك إجراء مطلوب منك.",
        "before_you_start": "راجع المخطط الزمني قبل رفع أي ملف جديد حتى تتأكد من آخر تحديث على الطلب.",
        "step_by_step_guide": "1. اقرأ الحالة الحالية أعلى الصفحة.\n2. راجع المستندات المرفوعة والملاحظات الظاهرة لك.\n3. إذا وُجد طلب نقص، افتح شاشة الرد على النواقص من الرابط المخصص.",
        "expected_result": "تفهم سبب توقف الطلب أو تقدمه دون الحاجة للتواصل مع الفريق في كل مرة.",
        "common_errors": "رفع ملف من شاشة غير مخصصة للنواقص.\nعدم مراجعة آخر ملاحظة قبل الرد.",
        "related_screen": "customer_missing_documents",
        "related_permission": "",
        "search_keywords": "تفاصيل طلب عميل حالة مستندات",
        "display_order": 40,
    },
    {
        "screen_key": "customer_missing_documents",
        "route_path": HELP_SCREEN_MAP["customer_missing_documents"]["route_path"],
        "role": "customer",
        "title": "الرد على طلب المستندات الناقصة",
        "short_description": "اتبع هذه الخطوات لإرجاع الطلب إلى المراجعة بسرعة.",
        "purpose": "توضح الشاشة ما هو المطلوب بالضبط وكيف ترفع النسخة المناسبة لكل مستند.",
        "before_you_start": "استخدم ملفات واضحة وحديثة وسمِّ كل ملف بما يوضح نوعه إن أمكن.",
        "step_by_step_guide": "1. اقرأ ملاحظة النقص كاملة.\n2. حدّد كل مستند مطلوب من القائمة.\n3. ارفع الملفات الناقصة ثم راجع نجاح الرفع.\n4. عد إلى تفاصيل الطلب لمتابعة تغير الحالة.",
        "expected_result": "تُرسل الملفات المطلوبة ويعود الطلب إلى قائمة المراجعة الداخلية.",
        "common_errors": "رفع ملف لا يطابق نوع المستند المطلوب.\nإرسال صورة غير واضحة أو ناقصة.",
        "related_screen": "customer_order_details",
        "related_permission": "",
        "search_keywords": "نواقص مستندات رفع رد عميل",
        "display_order": 50,
    },
    {
        "screen_key": "employee_dashboard",
        "route_path": HELP_SCREEN_MAP["employee_dashboard"]["route_path"],
        "role": "employee",
        "title": "لوحة الموظف",
        "short_description": "ملخص سريع للطوابير التي تحتاج إلى معالجة فورية.",
        "purpose": "توضح لك الشاشة أين يوجد تراكم في المراجعات أو الطلبات القريبة من الموعد.",
        "before_you_start": "ابدأ بالأقسام ذات الأولوية أو التي تحتوي على طلبات متأخرة.",
        "step_by_step_guide": "1. راجع أرقام الملخص في أعلى اللوحة.\n2. افتح قائمة المراجعة أو التحقق من الوثائق حسب الأولوية.\n3. عد إلى اللوحة بعد كل دفعة عمل لمراجعة الوضع الحالي.",
        "expected_result": "تحدد أولويات العمل اليومية بسرعة وتنتقل مباشرة إلى الشاشة المناسبة.",
        "common_errors": "البدء بطلب منخفض الأولوية وترك الطلبات المتأخرة.\nتجاهل مؤشرات الوثائق الراجعة من العميل.",
        "related_screen": "employee_review_queue",
        "related_permission": "orders.review_order",
        "search_keywords": "لوحة موظف أولويات مراجعة",
        "display_order": 10,
    },
    {
        "screen_key": "employee_review_queue",
        "route_path": HELP_SCREEN_MAP["employee_review_queue"]["route_path"],
        "role": "employee",
        "title": "قائمة مراجعة الطلبات",
        "short_description": "استخدم المرشحات للعثور على الطلب المناسب وفتح المراجعة.",
        "purpose": "تساعد هذه الشاشة على تنظيم العمل حسب الحالة أو الخدمة أو التعيين.",
        "before_you_start": "راجع المرشح الحالي حتى لا تعمل على مجموعة طلبات غير مقصودة.",
        "step_by_step_guide": "1. استخدم البحث أو المرشحات لتحديد الطلبات المطلوبة.\n2. افتح الطلب من الجدول لمراجعة التفاصيل.\n3. انتقل إلى شاشة التحقق من الوثائق إذا احتجت التحقق التفصيلي.",
        "expected_result": "تصل إلى الطلب الصحيح بسرعة مع تقليل التنقل بين الشاشات.",
        "common_errors": "فتح طلب غير مخصص لك بدون مراجعة المرشح.\nالاعتماد على الصف الملخص دون فتح التفاصيل.",
        "related_screen": "employee_order_review",
        "related_permission": "orders.review_order",
        "search_keywords": "قائمة مراجعة موظف بحث طلبات",
        "display_order": 20,
    },
    {
        "screen_key": "employee_order_review",
        "route_path": HELP_SCREEN_MAP["employee_order_review"]["route_path"],
        "role": "employee",
        "title": "مراجعة الطلب",
        "short_description": "نفّذ المراجعة من داخل هذه الشاشة باستخدام الإجراءات المتاحة فقط.",
        "purpose": "تجمع هذه الشاشة بيانات العميل، الوثائق، الملاحظات، وخطوات العمل على الطلب.",
        "before_you_start": "تحقق من الحالة الحالية والوثائق المطلوبة قبل طلب نقص أو إسناد الطلب.",
        "step_by_step_guide": "1. راجع بيانات العميل والخدمة.\n2. تحقق من كل وثيقة مطلوبة.\n3. اطلب النواقص إذا كانت الوثائق غير مكتملة.\n4. اسند الطلب إلى مزود فقط بعد اكتمال التحقق.\n5. راجع النتيجة النهائية قبل الإكمال.",
        "expected_result": "يتقدم الطلب في المسار الصحيح مع تسجيل ملاحظات واضحة لكل خطوة.",
        "common_errors": "إسناد الطلب قبل اعتماد الوثائق.\nإكمال الطلب قبل مراجعة النتيجة النهائية.\nإرسال ملاحظة غير واضحة للعميل.",
        "related_screen": "employee_verify_documents",
        "related_permission": "orders.review_order",
        "search_keywords": "مراجعة طلب موظف إسناد نواقص",
        "display_order": 30,
    },
    {
        "screen_key": "employee_order_review",
        "route_path": HELP_SCREEN_MAP["employee_order_review"]["route_path"],
        "role": "employee",
        "permission_key": "orders.request_missing_documents",
        "workflow_status": "WAITING_CUSTOMER",
        "title": "متابعة الطلبات المنتظرة من العميل",
        "short_description": "إرشادات خاصة بالطلبات التي بانتظار رد العميل على النواقص.",
        "purpose": "تساعدك على التحقق من عودة المستندات المطلوبة قبل إعادة الطلب إلى المراجعة الداخلية.",
        "before_you_start": "راجع آخر طلب نقص وما إذا كانت أنواع المستندات المطلوبة قد رُفعت فعلاً.",
        "step_by_step_guide": "1. افتح سجل النواقص الحالي على الطلب.\n2. راجع الملفات الجديدة مقارنة بالقائمة المطلوبة.\n3. إذا كانت كاملة، استأنف المراجعة الداخلية.\n4. إذا بقي نقص، أرسل ملاحظة أوضح للعميل.",
        "expected_result": "لا يعود الطلب إلى المراجعة الداخلية إلا بعد اكتمال الاستجابة المطلوبة من العميل.",
        "common_errors": "إعادة الطلب إلى المراجعة قبل رفع جميع الملفات.\nالاعتماد على اسم الملف فقط دون فحص المحتوى.",
        "related_screen": "employee_verify_documents",
        "related_permission": "orders.request_missing_documents",
        "search_keywords": "انتظار العميل نواقص مستندات",
        "display_order": 31,
    },
    {
        "screen_key": "employee_verify_documents",
        "route_path": HELP_SCREEN_MAP["employee_verify_documents"]["route_path"],
        "role": "employee",
        "permission_key": "documents.verify_document",
        "title": "التحقق من الوثائق",
        "short_description": "راجع كل ملف واربط قرار التحقق بالحالة الفعلية للمستند.",
        "purpose": "تضمن هذه الشاشة أن الوثائق المقبولة والمرفوضة موثقة بشكل واضح.",
        "before_you_start": "افتح الطلب المرتبط إذا احتجت إلى مراجعة الخدمة أو قائمة المستندات المطلوبة.",
        "step_by_step_guide": "1. افتح المستند المطلوب من القائمة.\n2. راجع الجودة، النوع، والارتباط بالخدمة.\n3. اعتمد المستند أو ارفضه وفق النتيجة.\n4. عد إلى شاشة الطلب لمتابعة الإجراء التالي.",
        "expected_result": "يتضح للفريق أي الوثائق أصبحت معتمدة وأيها يحتاج إلى استبدال.",
        "common_errors": "اعتماد مستند غير مطابق للنوع المطلوب.\nرفض مستند بدون سبب واضح للفريق أو العميل.",
        "related_screen": "employee_order_review",
        "related_permission": "documents.verify_document",
        "search_keywords": "تحقق وثائق اعتماد رفض",
        "display_order": 40,
    },
    {
        "screen_key": "provider_dashboard",
        "route_path": HELP_SCREEN_MAP["provider_dashboard"]["route_path"],
        "role": "provider",
        "title": "لوحة المزود",
        "short_description": "تعرض هذه الشاشة ملخص الطلبات المعيّنة لك وحالتها الحالية.",
        "purpose": "تساعدك على معرفة الطلبات النشطة والجاهزة للتسليم النهائي.",
        "before_you_start": "ابدأ بالطلبات القريبة من الموعد أو التي تحمل ملاحظات جديدة.",
        "step_by_step_guide": "1. راجع أرقام الملخص في أعلى اللوحة.\n2. افتح قائمة الطلبات المعيّنة للوصول إلى العمل اليومي.\n3. تابع الطلبات الجاهزة للتسليم أولاً إذا كانت مكتملة.",
        "expected_result": "تتضح لك أولويات التنفيذ اليومية بدون الحاجة إلى البحث اليدوي.",
        "common_errors": "تجاهل الطلبات الجاهزة للتسليم.\nالاعتماد على الملخص دون فتح تفاصيل الطلب.",
        "related_screen": "provider_orders",
        "related_permission": "",
        "search_keywords": "لوحة مزود ملخص تنفيذ",
        "display_order": 10,
    },
    {
        "screen_key": "provider_orders",
        "route_path": HELP_SCREEN_MAP["provider_orders"]["route_path"],
        "role": "provider",
        "title": "الطلبات المعيّنة للمزود",
        "short_description": "قائمة تشغيلية للوصول السريع إلى الطلبات المرسلة إليك.",
        "purpose": "تُمكّنك من البحث عن الطلب حسب الرقم أو الخدمة أو المدينة ثم فتحه مباشرة.",
        "before_you_start": "استخدم البحث لتحديد الطلب الصحيح إذا كانت لديك عدة طلبات متشابهة.",
        "step_by_step_guide": "1. راجع حالة كل طلب من الجدول.\n2. استخدم البحث عند الحاجة.\n3. افتح تفاصيل الطلب لبدء التنفيذ أو استكماله.",
        "expected_result": "تصل بسرعة إلى الطلب الصحيح وتتعرف على حالته قبل فتحه.",
        "common_errors": "فتح طلب مشابه بالرقم أو المدينة عن طريق الخطأ.\nترك الطلب في القائمة دون تحديث حالته بعد العمل عليه.",
        "related_screen": "provider_order_details",
        "related_permission": "",
        "search_keywords": "طلبات مزود قائمة بحث",
        "display_order": 20,
    },
    {
        "screen_key": "provider_order_details",
        "route_path": HELP_SCREEN_MAP["provider_order_details"]["route_path"],
        "role": "provider",
        "title": "تفاصيل الطلب للمزود",
        "short_description": "نفّذ الطلب، أضف الملاحظات، وارفع الملف النهائي من هذه الشاشة.",
        "purpose": "تجمع هذه الشاشة كل ما يحتاجه المزود للعمل على الطلب المعيّن إليه.",
        "before_you_start": "راجع ملاحظات الإسناد والمستندات الحالية قبل تحديث الحالة.",
        "step_by_step_guide": "1. اقرأ وصف الخدمة والملاحظات المرتبطة بالطلب.\n2. حدّث الحالة بما يعكس التقدم الفعلي.\n3. أضف ملاحظة للمراجعة الداخلية عند الحاجة.\n4. ارفع المستند النهائي بعد اكتمال المعالجة.",
        "expected_result": "تصل النتيجة النهائية إلى الفريق الداخلي مع توثيق واضح لتقدم التنفيذ.",
        "common_errors": "رفع نسخة أولية بدل الملف النهائي.\nتحديث الحالة دون إرفاق ملاحظة عند الحاجة.",
        "related_screen": "provider_orders",
        "related_permission": "",
        "search_keywords": "تفاصيل مزود رفع نهائي ملاحظة",
        "display_order": 30,
    },
    {
        "screen_key": "employee_missing_service_requests",
        "route_path": HELP_SCREEN_MAP["employee_missing_service_requests"]["route_path"],
        "role": "support",
        "title": "طلبات الخدمات الجديدة لفريق الدعم",
        "short_description": "استخدم هذه الشاشة لمتابعة الطلبات التي لم تجد خدمة مناسبة بعد.",
        "purpose": "تمكّنك من مراجعة طلبات العملاء للخدمات غير الموجودة وربطها بخدمات حالية أو متابعتها داخلياً.",
        "before_you_start": "راجع الوصف المدخل من العميل قبل اقتراح خدمة مرتبطة أو تحديث الحالة.",
        "step_by_step_guide": "1. افتح الطلب المطلوب من القائمة.\n2. راجع اسم الخدمة والرسالة المدخلة.\n3. اربط الطلب بخدمة حالية إذا كانت مناسبة.\n4. حدّث الحالة أو أضف ملاحظة داخلية للمتابعة.",
        "expected_result": "يتم التعامل مع طلبات الخدمات الجديدة بسرعة دون ضياع تفاصيل العميل.",
        "common_errors": "ربط الطلب بخدمة غير مناسبة.\nإغلاق الطلب بدون توثيق سبب المتابعة.",
        "related_screen": "employee_service_categories",
        "related_permission": "",
        "search_keywords": "دعم طلبات خدمات جديدة",
        "display_order": 10,
    },
    {
        "screen_key": "employee_service_categories",
        "route_path": HELP_SCREEN_MAP["employee_service_categories"]["route_path"],
        "role": "support",
        "title": "تصنيفات الخدمات للدعم",
        "short_description": "أدر التصنيفات من هذه الشاشة فقط عند الحاجة الفعلية للتنظيم.",
        "purpose": "تساعدك الشاشة على تنظيم ظهور الخدمات وربطها بهيكل واضح للعملاء والفريق الداخلي.",
        "before_you_start": "راجع ما إذا كان التعديل يخص تصنيفاً فعلياً أم خدمة منفردة قبل التنفيذ.",
        "step_by_step_guide": "1. ابحث عن التصنيف الحالي.\n2. أضف أو عدّل الاسم والظهور في الموقع عند الحاجة.\n3. راجع الترتيب والأب/الفرع قبل الحفظ.",
        "expected_result": "يبقى هيكل التصنيفات واضحاً ومنظماً للواجهة العامة والإدارة الداخلية.",
        "common_errors": "نقل خدمة إلى تصنيف غير مناسب.\nإنشاء تصنيف جديد بينما يكفي تعديل الموجود.",
        "related_screen": "employee_service_relations",
        "related_permission": "",
        "search_keywords": "دعم تصنيفات خدمات",
        "display_order": 20,
    },
    {
        "screen_key": "employee_service_relations",
        "route_path": HELP_SCREEN_MAP["employee_service_relations"]["route_path"],
        "role": "support",
        "title": "علاقات الخدمات للدعم",
        "short_description": "استخدم هذه الشاشة لاقتراح أو إدارة العلاقات بين الخدمات الفعلية.",
        "purpose": "تمنع العلاقات الصحيحة من توجيه العميل إلى خدمة غير مناسبة أو تكرار خطوات غير مطلوبة.",
        "before_you_start": "راجع الخدمة المصدر والخدمة الهدف قبل حفظ العلاقة.",
        "step_by_step_guide": "1. حدّد الخدمة الأساسية.\n2. اختر الخدمة المرتبطة ونوع العلاقة.\n3. اكتب رسالة واضحة للعميل إذا كانت العلاقة تظهر له.\n4. راجع أثر العلاقة قبل الحفظ.",
        "expected_result": "تظهر العلاقات المفيدة فقط وتبقى مسارات الخدمات مترابطة بشكل صحيح.",
        "common_errors": "إنشاء علاقة دائرية.\nربط خدمة بديلة كأنها شرط إلزامي.",
        "related_screen": "employee_service_categories",
        "related_permission": "",
        "search_keywords": "دعم علاقات خدمات اقتراح",
        "display_order": 30,
    },
    {
        "screen_key": "admin_dashboard",
        "route_path": HELP_SCREEN_MAP["admin_dashboard"]["route_path"],
        "role": "admin",
        "title": "لوحة الإدارة",
        "short_description": "شاشة دخول سريعة إلى الأقسام الإدارية المتخصصة.",
        "purpose": "تمكّنك من الوصول إلى إدارة الطلبات والخدمات والمستخدمين والتقارير من نقطة واحدة.",
        "before_you_start": "افتح القسم المتخصص المناسب بدلاً من محاولة تنفيذ كل شيء من لوحة الإدارة.",
        "step_by_step_guide": "1. راجع الملخصات أو البطاقات المتاحة.\n2. افتح شاشة الإدارة المناسبة للمهمة الحالية.\n3. ارجع إلى اللوحة عند الحاجة للتنقل إلى قسم آخر.",
        "expected_result": "تنتقل إلى الشاشة الصحيحة بسرعة وتقل الأخطاء الناتجة عن العمل من مكان غير مناسب.",
        "common_errors": "محاولة إدارة بيانات تفصيلية من شاشة غير مخصصة.\nفتح عدة أقسام دون تحديد أولوية واضحة.",
        "related_screen": "admin_orders",
        "related_permission": "",
        "search_keywords": "لوحة إدارة أقسام",
        "display_order": 10,
    },
    {
        "screen_key": "admin_users_roles",
        "route_path": HELP_SCREEN_MAP["admin_users_roles"]["route_path"],
        "role": "admin",
        "permission_key": "accounts.manage_user_roles",
        "title": "إدارة المستخدمين والأدوار",
        "short_description": "أضف المستخدمين التشغيليين، عدّل أدوارهم، ووزّع صلاحياتهم من هذه الشاشة.",
        "purpose": "تضمن الشاشة أن إنشاء الحسابات الإدارية والتشغيلية يتم من مكان واحد وبصلاحيات منضبطة.",
        "before_you_start": "تحقق من الدور المطلوب للمستخدم قبل الإنشاء أو التعديل، وراجع تبويب الصلاحيات للمستخدم الحالي.",
        "step_by_step_guide": "1. استخدم البحث للعثور على المستخدم الحالي.\n2. افتح التعديل لتغيير البيانات أو الدور.\n3. انتقل إلى تبويب الصلاحيات عند الحاجة إلى إذن دقيق.\n4. عطّل الحساب فقط إذا لم يعد مطلوباً.",
        "expected_result": "تظل الحسابات والصلاحيات محدثة بدون منح وصول زائد أو غير مقصود.",
        "common_errors": "منح دور إداري بدل دور تشغيلي.\nتعطيل مستخدم ما زال عليه عمل نشط.",
        "related_screen": "admin_help_guides",
        "related_permission": "accounts.manage_user_roles",
        "search_keywords": "إدارة مستخدمين أدوار صلاحيات",
        "display_order": 20,
    },
    {
        "screen_key": "admin_services",
        "route_path": HELP_SCREEN_MAP["admin_services"]["route_path"],
        "role": "admin",
        "title": "إدارة الخدمات",
        "short_description": "شاشة إدارة تفاصيل الخدمات والأسعار والمستندات المطلوبة والخصائص الأساسية.",
        "purpose": "تجمع الشاشة ما يخص تعريف الخدمة نفسها حتى لا يتشتت تحديثها عبر أقسام متعددة.",
        "before_you_start": "راجع التصنيف أولاً وتأكد أن الخدمة النشطة لا ترتبط ببيانات قديمة أو ناقصة.",
        "step_by_step_guide": "1. ابحث عن الخدمة أو أنشئ خدمة جديدة.\n2. حدّث الاسم والوصف والرسوم والمدة المتوقعة.\n3. راجع المستندات المطلوبة والخصائص التشغيلية.\n4. احفظ ثم اختبر ظهور الخدمة في المسار الصحيح.",
        "expected_result": "تُدار الخدمة من شاشة واحدة وتبقى بياناتها التشغيلية متسقة.",
        "common_errors": "ترك الرسوم أو مدة التنفيذ غير محدثة.\nتعطيل خدمة مستخدمة دون مراجعة أثر الطلبات الحالية.",
        "related_screen": "admin_service_categories",
        "related_permission": "",
        "search_keywords": "إدارة خدمات أسعار مستندات",
        "display_order": 30,
    },
    {
        "screen_key": "admin_service_categories",
        "route_path": HELP_SCREEN_MAP["admin_service_categories"]["route_path"],
        "role": "admin",
        "title": "إدارة تصنيفات الخدمات",
        "short_description": "أنشئ هيكل التصنيفات وراجع ترتيبه قبل تعديل ظهور الخدمات.",
        "purpose": "تضمن الشاشة أن بنية التصنيفات منطقية وواضحة للموقع والإدارة.",
        "before_you_start": "تأكد أن التعديل المطلوب يخص التصنيف نفسه وليس بيانات خدمة منفردة.",
        "step_by_step_guide": "1. راجع الأب والفرع الحاليين.\n2. عدّل الاسم أو الترتيب أو الظهور حسب الحاجة.\n3. احفظ ثم راجع أثر التعديل على قائمة الخدمات.",
        "expected_result": "تظهر التصنيفات بالترتيب الصحيح دون ازدواجية أو تعارض.",
        "common_errors": "إنشاء تصنيف مكرر.\nربط تصنيف فرعي بأب غير مناسب.",
        "related_screen": "admin_services",
        "related_permission": "",
        "search_keywords": "إدارة تصنيفات خدمات",
        "display_order": 40,
    },
    {
        "screen_key": "admin_service_relations",
        "route_path": HELP_SCREEN_MAP["admin_service_relations"]["route_path"],
        "role": "admin",
        "title": "إدارة علاقات الخدمات",
        "short_description": "أدر الشروط والبدائل والعلاقات اللاحقة بين الخدمات من هذه الشاشة.",
        "purpose": "تحافظ هذه الشاشة على تسلسل خدمات واضح وتقلل الطلبات التي تبدأ من خدمة غير مناسبة.",
        "before_you_start": "راجع نوع العلاقة المطلوب قبل الحفظ، خاصة العلاقات الشرطية.",
        "step_by_step_guide": "1. اختر الخدمة المصدر.\n2. حدّد الخدمة المرتبطة ونوع العلاقة.\n3. راجع رسالة العميل إن كانت العلاقة ظاهرة له.\n4. احفظ بعد التأكد من عدم وجود تعارض أو دائرة.",
        "expected_result": "تعمل الإرشادات بين الخدمات بشكل صحيح داخل مسار الطلب.",
        "common_errors": "إنشاء علاقة شرطية بين خدمتين غير مترابطتين.\nتكرار علاقة موجودة مسبقاً.",
        "related_screen": "admin_services",
        "related_permission": "",
        "search_keywords": "إدارة علاقات خدمات شروط بدائل",
        "display_order": 50,
    },
    {
        "screen_key": "admin_providers",
        "route_path": HELP_SCREEN_MAP["admin_providers"]["route_path"],
        "role": "admin",
        "title": "إدارة المزودين",
        "short_description": "تابع اعتماد المزودين، تفعيلهم، وبياناتهم التشغيلية.",
        "purpose": "تساعد الشاشة على ضبط من يمكن إسناد الطلبات إليه فعلياً.",
        "before_you_start": "تحقق من الاعتماد والتوفر قبل تعديل التفعيل أو الربط بالخدمات.",
        "step_by_step_guide": "1. ابحث عن المزود المطلوب.\n2. راجع حالة الاعتماد والتفعيل.\n3. حدّث البيانات التشغيلية اللازمة.\n4. انتقل إلى شاشة خدمات المزودين عند الحاجة إلى ربط خدمة محددة.",
        "expected_result": "يبقى فقط المزودون الجاهزون ظاهرين للإسناد الفعلي للطلبات.",
        "common_errors": "تفعيل مزود غير معتمد.\nترك بيانات المدينة أو التخصص غير محدثة.",
        "related_screen": "admin_provider_services",
        "related_permission": "",
        "search_keywords": "إدارة مزودين اعتماد تفعيل",
        "display_order": 60,
    },
    {
        "screen_key": "admin_reports",
        "route_path": HELP_SCREEN_MAP["admin_reports"]["route_path"],
        "role": "admin",
        "title": "التقارير الإدارية",
        "short_description": "راجع الأداء العام والاتجاهات التشغيلية من شاشة التقارير.",
        "purpose": "تمكنك الشاشة من متابعة مؤشرات الطلبات والإيرادات والأداء التشغيلي.",
        "before_you_start": "حدد الفترة أو المرشحات المناسبة قبل قراءة النتائج أو مشاركتها.",
        "step_by_step_guide": "1. اختر الفترة الزمنية المطلوبة.\n2. راجع مؤشرات الأداء الأساسية.\n3. استخدم النتائج لتحديد نقاط التأخير أو التحسن.\n4. عدّل المرشحات عند الحاجة للمقارنة.",
        "expected_result": "تحصل على قراءة واضحة للوضع التشغيلي بدل الاعتماد على الانطباع العام.",
        "common_errors": "قراءة تقرير بدون مراجعة الفترة.\nمقارنة أرقام من مرشحات مختلفة بدون توحيدها.",
        "related_screen": "admin_dashboard",
        "related_permission": "",
        "search_keywords": "تقارير إدارة أداء",
        "display_order": 70,
    },
    {
        "screen_key": "admin_public_site",
        "route_path": HELP_SCREEN_MAP["admin_public_site"]["route_path"],
        "role": "admin",
        "title": "إدارة الموقع العام",
        "short_description": "نقطة الوصول إلى محتوى الواجهة العامة والإعلانات والثيم.",
        "purpose": "تمنع هذه الشاشة تشتت تحديثات الموقع العام عبر أقسام متعددة غير مترابطة.",
        "before_you_start": "حدد ما إذا كان التعديل يخص المحتوى أو الإعلانات أو المظهر قبل متابعة العمل.",
        "step_by_step_guide": "1. افتح القسم المناسب من الشاشة.\n2. انتقل إلى المحتوى أو الإعلانات أو الثيم حسب المهمة.\n3. راجع المعاينة بعد أي تعديل مرئي.",
        "expected_result": "يتم تحديث الواجهة العامة من المسار الصحيح مع تقليل التعديلات غير المقصودة.",
        "common_errors": "تعديل المظهر عند الحاجة لتعديل المحتوى فقط.\nنسيان مراجعة المعاينة بعد التغيير.",
        "related_screen": "admin_homepage_content",
        "related_permission": "",
        "search_keywords": "موقع عام محتوى إعلانات ثيم",
        "display_order": 80,
    },
    {
        "screen_key": "admin_advertisements",
        "route_path": HELP_SCREEN_MAP["admin_advertisements"]["route_path"],
        "role": "admin",
        "title": "إدارة الإعلانات",
        "short_description": "أنشئ الإعلانات العامة وحدّث ترتيبها وفترات ظهورها.",
        "purpose": "تضمن الشاشة أن الرسائل الترويجية أو التنبيهية تظهر في المكان والوقت الصحيحين.",
        "before_you_start": "راجع تاريخ البداية والنهاية والترتيب قبل النشر.",
        "step_by_step_guide": "1. أنشئ الإعلان أو افتح إعلاناً موجوداً.\n2. حدّث النصوص والرابط والألوان الأساسية.\n3. راجع الترتيب وتاريخ الظهور.\n4. احفظ ثم راجع النتيجة من شاشة المعاينة.",
        "expected_result": "تظهر الإعلانات المطلوبة فقط وفق ترتيبها وحالتها النشطة.",
        "common_errors": "ترك إعلان منتهي مفعلاً.\nاستخدام رابط غير صحيح أو نص غير واضح.",
        "related_screen": "admin_public_site",
        "related_permission": "",
        "search_keywords": "إعلانات موقع عام",
        "display_order": 90,
    },
    {
        "screen_key": "admin_theme_settings",
        "route_path": HELP_SCREEN_MAP["admin_theme_settings"]["route_path"],
        "role": "admin",
        "title": "إعدادات المظهر العام",
        "short_description": "حدّث الألوان والثيم العام ثم راجع المعاينة قبل الاعتماد.",
        "purpose": "تحافظ هذه الشاشة على اتساق الهوية البصرية للموقع العام.",
        "before_you_start": "جهّز القيم اللونية أو التعديلات المطلوبة وراجع أثرها على النصوص والخلفيات.",
        "step_by_step_guide": "1. عدّل اللون أو الإعداد المرئي المطلوب.\n2. احفظ التغيير.\n3. افتح المعاينة للتأكد من الوضوح والاتساق.",
        "expected_result": "يظهر الثيم المحدث بشكل متناسق وقابل للقراءة.",
        "common_errors": "اختيار ألوان تقلل التباين.\nالحفظ بدون مراجعة المعاينة.",
        "related_screen": "admin_public_site",
        "related_permission": "",
        "search_keywords": "ثيم ألوان مظهر",
        "display_order": 100,
    },
    {
        "screen_key": "admin_notifications",
        "route_path": HELP_SCREEN_MAP["admin_notifications"]["route_path"],
        "role": "admin",
        "title": "إدارة قوالب الإشعارات",
        "short_description": "حدّث القوالب المعتمدة وراجع النصوص قبل استخدامها تشغيلياً.",
        "purpose": "تضمن الشاشة اتساق الرسائل التي تصل إلى العميل أو الفريق.",
        "before_you_start": "حدد القالب المطلوب وتجنب تغيير الرسائل النشطة دون مراجعة أثرها.",
        "step_by_step_guide": "1. افتح القالب المطلوب من القائمة.\n2. عدّل العنوان والنصوص المعتمدة.\n3. راجع المتغيرات المتاحة إن وجدت.\n4. احفظ ثم اختبر الاستخدام من المسار التشغيلي المناسب.",
        "expected_result": "تُرسل الإشعارات بصياغة موحدة وواضحة في الحالات التشغيلية الصحيحة.",
        "common_errors": "حذف متغير مطلوب من القالب.\nتعديل نص دون مراجعة معناه في جميع الحالات.",
        "related_screen": "admin_orders",
        "related_permission": "",
        "search_keywords": "إشعارات قوالب رسائل",
        "display_order": 110,
    },
    {
        "screen_key": "admin_help_guides",
        "route_path": HELP_SCREEN_MAP["admin_help_guides"]["route_path"],
        "role": "admin",
        "permission_key": "help_guides.manage_help_guides",
        "title": "إدارة دليل المستخدم داخل النظام",
        "short_description": "أنشئ محتوى المساعدة حسب الشاشة والدور والحالة التشغيلية.",
        "purpose": "تسمح لك الشاشة بإدارة المحتوى الذي يراه كل مستخدم من داخل التطبيق حسب دوره وصلاحياته.",
        "before_you_start": "اختر الشاشة الصحيحة والدور المناسب وحدد إن كان المحتوى عاماً أم مرتبطاً بحالة أو صلاحية محددة.",
        "step_by_step_guide": "1. أضف دليلاً جديداً أو افتح دليلاً موجوداً.\n2. اختر الشاشة والدور المطلوبين.\n3. حدّد صلاحية أو حالة تشغيلية عند الحاجة.\n4. اكتب الخطوات بلغة تشغيلية واضحة.\n5. راجع المعاينة ثم احفظ.",
        "expected_result": "يظهر للمستخدمين محتوى مساعدة دقيق يطابق الشاشة الحالية وصلاحياتهم.",
        "common_errors": "ربط الدليل بشاشة غير صحيحة.\nكتابة تعليمات عامة لا تطابق دور المستخدم.\nنسيان تعطيل نسخة قديمة بعد استبدالها.",
        "related_screen": "admin_users_roles",
        "related_permission": "help_guides.manage_help_guides",
        "search_keywords": "دليل مستخدم مساعدة شاشة دور",
        "display_order": 120,
    },
]


def seed_help_guides(apps, schema_editor):
    HelpGuide = apps.get_model("help_guides", "HelpGuide")
    for payload in SEED_GUIDES:
        lookup = {
            "screen_key": payload["screen_key"],
            "role": payload["role"],
            "title": payload["title"],
            "workflow_status": payload.get("workflow_status", ""),
        }
        HelpGuide.objects.update_or_create(defaults=payload, **lookup)


def unseed_help_guides(apps, schema_editor):
    HelpGuide = apps.get_model("help_guides", "HelpGuide")
    titles = [item["title"] for item in SEED_GUIDES]
    HelpGuide.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("help_guides", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_help_guides, unseed_help_guides),
    ]

