# Generated by Django 5.2.13 on 2026-06-02 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_guides", "0002_seed_help_guides"),
        ("services", "0007_service_organization_service_scope_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="helpguide",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="helpguide",
            name="main_workflow",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="helpguide",
            name="next_step",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="helpguide",
            name="when_to_use",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="HelpGuideAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screen_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("all_users", "All users"),
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                            ("employee", "Employee"),
                            ("support", "Support"),
                            ("provider", "Provider"),
                            ("platform_super_admin", "Platform super admin"),
                            ("platform_support", "Platform support"),
                            ("partner_owner", "Partner owner"),
                            ("partner_admin", "Partner admin"),
                            ("branch_manager", "Branch manager"),
                            ("partner_employee", "Partner employee"),
                            ("provider_admin", "Provider admin"),
                            ("provider_employee", "Provider employee"),
                            ("finance", "Finance"),
                            ("auditor", "Auditor"),
                        ],
                        db_index=True,
                        default="all_users",
                        max_length=40,
                    ),
                ),
                (
                    "permission_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("search_keywords", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("button_key", models.CharField(db_index=True, max_length=120)),
                ("button_label", models.CharField(max_length=255)),
                ("purpose", models.TextField(blank=True)),
                ("when_to_use", models.TextField(blank=True)),
                ("action_result", models.TextField(blank=True)),
                (
                    "status_before",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "status_after",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("notification_triggered", models.TextField(blank=True)),
                ("warning_message", models.TextField(blank=True)),
                ("common_errors", models.TextField(blank=True)),
                ("safety_rule", models.TextField(blank=True)),
                ("confirmation_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["screen_key", "display_order", "button_label", "id"],
                "indexes": [
                    models.Index(
                        fields=["screen_key", "role", "is_active"],
                        name="help_guides_screen__0433c8_idx",
                    ),
                    models.Index(
                        fields=["screen_key", "status_before", "is_active"],
                        name="help_guides_screen__b8f760_idx",
                    ),
                    models.Index(
                        fields=["button_key", "role", "is_active"],
                        name="help_guides_button__4f8673_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HelpGuideField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screen_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("all_users", "All users"),
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                            ("employee", "Employee"),
                            ("support", "Support"),
                            ("provider", "Provider"),
                            ("platform_super_admin", "Platform super admin"),
                            ("platform_support", "Platform support"),
                            ("partner_owner", "Partner owner"),
                            ("partner_admin", "Partner admin"),
                            ("branch_manager", "Branch manager"),
                            ("partner_employee", "Partner employee"),
                            ("provider_admin", "Provider admin"),
                            ("provider_employee", "Provider employee"),
                            ("finance", "Finance"),
                            ("auditor", "Auditor"),
                        ],
                        db_index=True,
                        default="all_users",
                        max_length=40,
                    ),
                ),
                (
                    "permission_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("search_keywords", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_key", models.CharField(db_index=True, max_length=120)),
                ("field_label", models.CharField(max_length=255)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("model_field", models.CharField(blank=True, max_length=120)),
                ("purpose", models.TextField(blank=True)),
                ("required", models.BooleanField(default=False)),
                ("editable", models.BooleanField(default=True)),
                ("data_type", models.CharField(blank=True, max_length=50)),
                ("accepted_format", models.TextField(blank=True)),
                ("valid_example", models.TextField(blank=True)),
                ("invalid_example", models.TextField(blank=True)),
                ("validation_rule", models.TextField(blank=True)),
                ("error_explanation", models.TextField(blank=True)),
                ("placeholder_text", models.TextField(blank=True)),
                ("tooltip_text", models.TextField(blank=True)),
                ("default_value", models.TextField(blank=True)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                ("who_can_edit", models.TextField(blank=True)),
                ("locked_when", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["screen_key", "display_order", "field_label", "id"],
                "indexes": [
                    models.Index(
                        fields=["screen_key", "role", "is_active"],
                        name="help_guides_screen__c31724_idx",
                    ),
                    models.Index(
                        fields=["field_key", "role", "is_active"],
                        name="help_guides_field_k_c108b0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HelpGuideService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screen_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("all_users", "All users"),
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                            ("employee", "Employee"),
                            ("support", "Support"),
                            ("provider", "Provider"),
                            ("platform_super_admin", "Platform super admin"),
                            ("platform_support", "Platform support"),
                            ("partner_owner", "Partner owner"),
                            ("partner_admin", "Partner admin"),
                            ("branch_manager", "Branch manager"),
                            ("partner_employee", "Partner employee"),
                            ("provider_admin", "Provider admin"),
                            ("provider_employee", "Provider employee"),
                            ("finance", "Finance"),
                            ("auditor", "Auditor"),
                        ],
                        db_index=True,
                        default="all_users",
                        max_length=40,
                    ),
                ),
                (
                    "permission_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("search_keywords", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                ("who_can_use", models.TextField(blank=True)),
                ("required_documents", models.TextField(blank=True)),
                ("optional_documents", models.TextField(blank=True)),
                ("required_data", models.TextField(blank=True)),
                ("prerequisites", models.TextField(blank=True)),
                ("related_services", models.TextField(blank=True)),
                ("workflow_summary", models.TextField(blank=True)),
                ("final_output", models.TextField(blank=True)),
                ("common_errors", models.TextField(blank=True)),
                ("common_rejection_reasons", models.TextField(blank=True)),
                ("common_missing_document_reasons", models.TextField(blank=True)),
                ("estimated_processing_time", models.TextField(blank=True)),
                ("price_rule", models.TextField(blank=True)),
                ("provider_requirement", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_guides",
                        to="services.service",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["service_id", "display_order", "role", "id"],
                "indexes": [
                    models.Index(
                        fields=["service", "role", "is_active"],
                        name="help_guides_service_e6b1f5_idx",
                    ),
                    models.Index(
                        fields=["screen_key", "role", "is_active"],
                        name="help_guides_screen__727f26_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HelpGuideWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screen_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("all_users", "All users"),
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                            ("employee", "Employee"),
                            ("support", "Support"),
                            ("provider", "Provider"),
                            ("platform_super_admin", "Platform super admin"),
                            ("platform_support", "Platform support"),
                            ("partner_owner", "Partner owner"),
                            ("partner_admin", "Partner admin"),
                            ("branch_manager", "Branch manager"),
                            ("partner_employee", "Partner employee"),
                            ("provider_admin", "Provider admin"),
                            ("provider_employee", "Provider employee"),
                            ("finance", "Finance"),
                            ("auditor", "Auditor"),
                        ],
                        db_index=True,
                        default="all_users",
                        max_length=40,
                    ),
                ),
                (
                    "permission_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("search_keywords", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workflow_key", models.CharField(db_index=True, max_length=120)),
                (
                    "current_status",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "action_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("action_label", models.CharField(blank=True, max_length=255)),
                (
                    "next_status",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("required_fields", models.TextField(blank=True)),
                ("system_effect", models.TextField(blank=True)),
                ("notification_effect", models.TextField(blank=True)),
                ("blocked_cases", models.TextField(blank=True)),
                ("correction_process", models.TextField(blank=True)),
                ("button_key", models.CharField(blank=True, max_length=120)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "screen_key",
                    "display_order",
                    "current_status",
                    "workflow_key",
                    "id",
                ],
                "indexes": [
                    models.Index(
                        fields=["screen_key", "current_status", "is_active"],
                        name="help_guides_screen__4a95ca_idx",
                    ),
                    models.Index(
                        fields=["workflow_key", "role", "is_active"],
                        name="help_guides_workflo_68d69e_idx",
                    ),
                ],
            },
        ),
    ]
