# Generated by Django 5.2.13 on 2026-05-03 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notifications.notificationtemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(("retry_count__lte", models.F("max_retries"))),
                name="notification_retry_count_lte_max_retries",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_read", False), ("read_at__isnull", True)),
                    models.Q(("is_read", True), ("read_at__isnull", False)),
                    _connector="OR",
                ),
                name="notification_read_state_consistent",
            ),
        ),
    ]
