# Generated by Django 5.2.13 on 2026-05-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_template_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("send_manual_notification", "Can send manual notifications")
                ],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
