# Generated by Django 5.2.13 on 2026-05-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("providers", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to="providers.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="orderassignmenthistory",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderassignmenthistory",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_assignments_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderassignmenthistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_history",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderissue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_order_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderissue",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderissue",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_order_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordernote",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="ordernote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderstatuslog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderstatuslog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_orde_status_25e057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["priority", "created_at"], name="orders_orde_priorit_44dae2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "created_at"], name="orders_orde_custome_242823_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["assigned_provider", "status"],
                name="orders_orde_assigne_cb1d8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["city", "status"], name="orders_orde_city_78a057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["expected_delivery_date"], name="orders_orde_expecte_d41167_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordernote",
            index=models.Index(
                fields=["order", "created_at"], name="orders_orde_order_i_0b1c52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordernote",
            index=models.Index(
                fields=["visibility", "created_at"],
                name="orders_orde_visibil_f8a877_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordernote",
            index=models.Index(
                fields=["user", "created_at"], name="orders_orde_user_id_b0ac61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatuslog",
            index=models.Index(
                fields=["order", "created_at"], name="orders_orde_order_i_93aa9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatuslog",
            index=models.Index(
                fields=["new_status", "created_at"],
                name="orders_orde_new_sta_7be6de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatuslog",
            index=models.Index(
                fields=["changed_by", "created_at"],
                name="orders_orde_changed_7fbce5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["customer", "created_at"], name="orders_rati_custome_565d8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(fields=["score"], name="orders_rati_score_3c43d8_idx"),
        ),
    ]
