# Generated by Django 5.2.13 on 2026-05-03 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
        ("providers", "0002_initial"),
        ("services", "0002_address_services_ad_user_id_244737_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_price__gte", 0),
                    ("final_price__isnull", True),
                    _connector="OR",
                ),
                name="order_final_price_gte_0",
            ),
        ),
    ]
