# Generated by Django 5.2.13 on 2026-05-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_order_final_price_gte_0"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("review_order", "Can review orders"),
                    ("request_missing_documents", "Can request missing documents"),
                    ("assign_order", "Can assign orders"),
                    ("complete_order", "Can complete orders"),
                    ("reject_order", "Can reject orders"),
                    ("view_reports_dashboard", "Can view reports dashboard"),
                ],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
