# Generated by Django 5.2.13 on 2026-05-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("submit_order", "Can submit orders"),
                    ("cancel_order", "Can cancel orders"),
                    ("review_order", "Can review orders"),
                    ("request_missing_documents", "Can request missing documents"),
                    ("assign_order", "Can assign orders"),
                    ("process_order", "Can process provider work"),
                    ("complete_order", "Can complete orders"),
                    ("reject_order", "Can reject orders"),
                    ("manage_order_workflow", "Can manage order workflow"),
                    ("view_reports_dashboard", "Can view reports dashboard"),
                    ("export_order_reports", "Can export order reports"),
                ],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
