# Generated by Django 5.2.13 on 2026-05-04 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_options"),
        ("providers", "0002_initial"),
        ("services", "0003_alter_service_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Current internal employee owner of the order.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_employee_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["assigned_employee", "status"],
                name="orders_orde_assigne_1f52f2_idx",
            ),
        ),
    ]
