# Generated by Django 5.2.13 on 2026-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_assigned_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="missing_document_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Requested customer uploads still required to move the order forward.",
            ),
        ),
    ]
