# Generated by Django 5.2.13 on 2026-05-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_missingdocumentrequest"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="missingdocumentrequest",
            new_name="orders_miss_order_i_f16d8d_idx",
            old_name="orders_miss_order_i_req_at_idx",
        ),
        migrations.RenameIndex(
            model_name="missingdocumentrequest",
            new_name="orders_miss_is_reso_cd6e5f_idx",
            old_name="orders_miss_resolved_req_at_idx",
        ),
    ]
