# Generated by Django 5.2.13 on 2026-05-16 17:03

from django.db import migrations, models


def backfill_order_service_snapshots(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.select_related("service", "service__category").all():
        updates = {}
        if not order.service_name_snapshot and getattr(order.service, "name_ar", ""):
            updates["service_name_snapshot"] = order.service.name_ar
        category = getattr(order.service, "category", None)
        if not order.service_category_name_snapshot and category is not None:
            updates["service_category_name_snapshot"] = category.name_ar
        if updates:
            Order.objects.filter(pk=order.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_add_order_deleted_status_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="service_category_name_snapshot",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service_name_snapshot",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.RunPython(backfill_order_service_snapshots, migrations.RunPython.noop),
    ]
