# Generated by Django 5.2.13 on 2026-05-16 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_order_organization_data(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    CustomerProfile = apps.get_model("accounts", "CustomerProfile")
    Organization = apps.get_model("organizations", "Organization")
    fallback_partner = Organization.objects.filter(organization_type="partner", is_active=True).order_by("created_at").first()
    fallback_platform = Organization.objects.filter(organization_type="platform", is_active=True).order_by("created_at").first()
    fallback_org = fallback_partner or fallback_platform

    for order in Order.objects.select_related("service", "customer", "assigned_provider", "assigned_provider__organization").all():
        changed = []
        organization = order.organization
        if organization is None:
            if getattr(order.service, "organization_id", None):
                organization = order.service.organization
            else:
                customer_profile = CustomerProfile.objects.filter(user_id=order.customer_id).first()
                if customer_profile and getattr(customer_profile, "organization_id", None):
                    organization = customer_profile.organization
                else:
                    organization = fallback_org
            if organization is not None:
                order.organization = organization
                changed.append("organization")
        if organization is not None and not order.organization_name_snapshot:
            order.organization_name_snapshot = organization.name
            changed.append("organization_name_snapshot")
        assigned_provider = getattr(order, "assigned_provider", None)
        provider_org = getattr(assigned_provider, "organization", None)
        if provider_org is not None and order.assigned_provider_organization_id != provider_org.pk:
            order.assigned_provider_organization = provider_org
            changed.append("assigned_provider_organization")
        if changed:
            order.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customerprofile_organization"),
        ("orders", "0010_order_service_category_name_snapshot_and_more"),
        ("organizations", "0001_initial"),
        ("providers", "0003_providerprofile_organization"),
        ("services", "0007_service_organization_service_scope_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_provider_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_provider_orders",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="organizations.branch",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="organization_name_snapshot",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["organization", "status"], name="orders_orde_organiz_b4ac87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["branch", "status"], name="orders_orde_branch__e95c01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["assigned_provider_organization", "status"],
                name="orders_orde_assigne_12a32b_idx",
            ),
        ),
        migrations.RunPython(
            backfill_order_organization_data,
            migrations.RunPython.noop,
        ),
    ]
