# Generated by Django 5.1.11 on 2026-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_assigned_provider_organization_order_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="expected_delivery_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="expected_delivery_mode",
            field=models.CharField(blank=True, default="duration", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="expected_delivery_note_snapshot",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="expected_delivery_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="expected_duration_unit_snapshot",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="expected_duration_value_snapshot",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
