# Generated by Django 5.1.11 on 2026-10-04 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_orderissue_delete_reason_orderissue_deleted_at_and_more"),
        ("organizations", "0002_branch_delete_reason_branch_deleted_at_and_more"),
        ("providers", "0004_providerprofile_delete_reason_and_more"),
        ("services", "0011_backfill_required_document_definitions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="submission_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="submission_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("customer", "submission_key"),
                name="unique_customer_order_submission_key",
            ),
        ),
    ]
