# Generated by Django 5.2.13 on 2026-05-16 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_platform_organization(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    OrganizationBranding = apps.get_model("organizations", "OrganizationBranding")
    organization, _ = Organization.objects.get_or_create(
        slug="platform-owner",
        defaults={
            "name": "Platform Owner",
            "organization_type": "platform",
            "legal_name": "Platform Owner",
            "is_active": True,
        },
    )
    OrganizationBranding.objects.get_or_create(organization=organization)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "services",
            "0006_alter_servicecategory_options_servicecategory_color_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "organization_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("partner", "Partner"),
                            ("provider", "Provider"),
                            ("customer_company", "Customer company"),
                        ],
                        max_length=30,
                    ),
                ),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("tax_number", models.CharField(blank=True, max_length=100)),
                (
                    "commercial_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "manage_organizations",
                        "Can manage organizations, branches, branding, and memberships",
                    ),
                    (
                        "manage_partner_service_config",
                        "Can manage partner service catalog configuration",
                    ),
                    ("view_cross_tenant_data", "Can view cross-tenant data"),
                    (
                        "manage_billing_settings",
                        "Can manage billing settings and commission rules",
                    ),
                ],
                "indexes": [
                    models.Index(fields=["slug"], name="organizatio_slug_048085_idx"),
                    models.Index(
                        fields=["organization_type", "is_active"],
                        name="organizatio_organiz_6c4755_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="organizatio_is_acti_1ffc28_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("branch_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizations/branding/"
                    ),
                ),
                ("primary_color", models.CharField(blank=True, max_length=20)),
                ("secondary_color", models.CharField(blank=True, max_length=20)),
                ("public_site_title", models.CharField(blank=True, max_length=255)),
                ("public_site_description", models.TextField(blank=True)),
                ("show_public_page", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "membership_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_super_admin", "Platform super admin"),
                            ("platform_support", "Platform support"),
                            ("partner_owner", "Partner owner"),
                            ("partner_admin", "Partner admin"),
                            ("branch_manager", "Branch manager"),
                            ("partner_employee", "Partner employee"),
                            ("provider_admin", "Provider admin"),
                            ("provider_employee", "Provider employee"),
                            ("finance", "Finance"),
                            ("auditor", "Auditor"),
                            ("customer", "Customer"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name", "role", "user__full_name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("custom_name", models.CharField(blank=True, max_length=255)),
                (
                    "custom_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("visible_to_customers", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        limit_choices_to={"organization_type": "partner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_service_configs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_configs",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name", "service__name_ar"],
            },
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["organization", "is_active"],
                name="organizatio_organiz_02ed07_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_branch_name_per_organization",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "role", "is_active"],
                name="organizatio_organiz_b3d0b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["user", "is_active"], name="organizatio_user_id_494b92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["branch", "is_active"], name="organizatio_branch__5df9e6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "organization", "branch", "role"),
                name="unique_membership_per_user_org_branch_role",
            ),
        ),
        migrations.AddIndex(
            model_name="partnerserviceconfig",
            index=models.Index(
                fields=["organization", "is_enabled", "visible_to_customers"],
                name="organizatio_organiz_57f2df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnerserviceconfig",
            index=models.Index(
                fields=["service", "is_enabled"], name="organizatio_service_06c927_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerserviceconfig",
            constraint=models.UniqueConstraint(
                fields=("organization", "service"),
                name="unique_partner_service_config_per_org_service",
            ),
        ),
        migrations.RunPython(
            create_default_platform_organization,
            migrations.RunPython.noop,
        ),
    ]
