# Generated by Django 5.2.13 on 2026-05-03 19:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                ("category_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_categories/images/"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service category",
                "verbose_name_plural": "Service categories",
                "ordering": ["display_order", "name_ar"],
                "indexes": [
                    models.Index(fields=["slug"], name="services_se_slug_89aee3_idx"),
                    models.Index(
                        fields=["is_active"], name="services_se_is_acti_d8f4e5_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="services_se_display_0fd670_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "service_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated service number, example: SRV-000001.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("short_description_ar", models.CharField(blank=True, max_length=300)),
                ("short_description_en", models.CharField(blank=True, max_length=300)),
                ("description_ar", models.TextField()),
                ("description_en", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="services/images/"
                    ),
                ),
                (
                    "required_information_schema",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Dynamic fields required from client when ordering this service.",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed price"),
                            ("starts_from", "Starts from"),
                            ("quotation", "Requires quotation"),
                            ("free", "Free"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "government_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "estimated_duration_unit",
                    models.CharField(
                        choices=[
                            ("hours", "Hours"),
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                ("terms_ar", models.TextField(blank=True)),
                ("terms_en", models.TextField(blank=True)),
                (
                    "is_online",
                    models.BooleanField(
                        default=True,
                        help_text="Can clients request this service online?",
                    ),
                ),
                ("requires_appointment", models.BooleanField(default=False)),
                (
                    "requires_manual_review",
                    models.BooleanField(
                        default=True,
                        help_text="Employee must review the order before processing.",
                    ),
                ),
                (
                    "provider_required",
                    models.BooleanField(
                        default=True,
                        help_text="This service requires a service provider to execute it.",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["display_order", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="ServiceProviderAssignment",
            fields=[
                (
                    "assignment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_assignments",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_assignments",
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequiredDocument",
            fields=[
                (
                    "requirement_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("document_type", models.CharField(max_length=120)),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("is_required", models.BooleanField(default=True)),
                ("allowed_extensions", models.JSONField(blank=True, default=list)),
                ("max_file_size", models.PositiveBigIntegerField(default=10485760)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requirements",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name_ar"],
            },
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["slug"], name="services_se_slug_4657d0_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["service_number"], name="services_se_service_07ad23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_active"], name="services_se_is_acti_91b7ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_featured"], name="services_se_is_feat_35b40d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_online"], name="services_se_is_onli_cf22ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["display_order"], name="services_se_display_381b7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["category", "is_active"], name="services_se_categor_b50c86_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gte", 0)),
                name="service_base_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(("government_fee__gte", 0)),
                name="service_government_fee_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(("service_fee__gte", 0)),
                name="service_service_fee_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_duration__gte", 1)),
                name="service_estimated_duration_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceproviderassignment",
            constraint=models.UniqueConstraint(
                fields=("service", "provider"),
                name="unique_service_provider_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequireddocument",
            constraint=models.UniqueConstraint(
                fields=("service", "document_type"),
                name="unique_service_required_document_type",
            ),
        ),
    ]
