# Generated by Django 5.2.13 on 2026-05-03 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "is_default"], name="services_ad_user_id_244737_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["city"], name="services_ad_city_77fe17_idx"),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="unique_default_address_per_user",
            ),
        ),
    ]
