# Generated by Django 5.2.13 on 2026-05-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_address_services_ad_user_id_244737_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["display_order", "name_ar"],
                "permissions": [
                    ("manage_service_prices", "Can manage services and prices")
                ],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
    ]
