# Generated by Django 5.2.13 on 2026-05-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_servicerequireddocument_rule_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRelation",
            fields=[
                ("relation_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("prerequisite", "Required first"),
                            ("recommended_after", "Recommended after completion"),
                            ("optional_bundle", "Optional bundle"),
                            ("alternative", "Alternative option"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("message_to_customer", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_service_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="services.service",
                    ),
                ),
                (
                    "target_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service relation",
                "verbose_name_plural": "Service relations",
                "ordering": [
                    "source_service__name_ar",
                    "target_service__name_ar",
                    "relation_type",
                ],
                "indexes": [
                    models.Index(
                        fields=["source_service", "relation_type", "is_active"],
                        name="services_se_source__bbfc2a_idx",
                    ),
                    models.Index(
                        fields=["target_service", "relation_type", "is_active"],
                        name="services_se_target__82ec1f_idx",
                    ),
                    models.Index(
                        fields=["is_active", "relation_type"],
                        name="services_se_is_acti_f3f880_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_service", "target_service", "relation_type"),
                        name="unique_service_relation_per_type",
                    )
                ],
            },
        ),
    ]
