# Generated by Django 5.2.13 on 2026-05-16 17:03

import django.db.models.deletion
from django.db import migrations, models


def backfill_category_sort_order(apps, schema_editor):
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    for category in ServiceCategory.objects.all().only("pk", "display_order", "sort_order"):
        category.sort_order = category.display_order
        category.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_servicerelation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "ordering": ["sort_order", "display_order", "name_ar"],
                "verbose_name": "Service category",
                "verbose_name_plural": "Service categories",
            },
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="services.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="show_on_public_site",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["sort_order"], name="services_se_sort_or_ac189b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["parent", "is_active"], name="services_se_parent__5a2713_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["show_on_public_site"], name="services_se_show_on_d72148_idx"
            ),
        ),
        migrations.RunPython(backfill_category_sort_order, migrations.RunPython.noop),
    ]
