# Generated by Django 5.2.13 on 2026-05-16 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        (
            "services",
            "0006_alter_servicecategory_options_servicecategory_color_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="scope",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("partner_private", "Partner private"),
                    ("partner_customized", "Partner customized"),
                ],
                db_index=True,
                default="global",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["organization", "scope", "is_active"],
                name="services_se_organiz_9f22cb_idx",
            ),
        ),
    ]
