# Generated by Django 5.1.11 on 2026-06-29 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_required_documents(apps, schema_editor):
    ServiceRequiredDocument = apps.get_model("services", "ServiceRequiredDocument")
    RequiredDocumentDefinition = apps.get_model("services", "RequiredDocumentDefinition")

    definitions_by_code = {}
    existing_definitions = RequiredDocumentDefinition.objects.all()
    for definition in existing_definitions:
        definitions_by_code[definition.code] = definition

    requirements = ServiceRequiredDocument.objects.all().order_by("requirement_id")
    for requirement in requirements:
        code = (requirement.document_type or "").strip().lower().replace(" ", "_")
        if not code:
            code = f"document_{requirement.requirement_id}"

        definition = definitions_by_code.get(code)
        if definition is None:
            definition = RequiredDocumentDefinition.objects.create(
                code=code,
                name_ar=requirement.name_ar or code,
                name_en=requirement.name_en or "",
                allowed_extensions=requirement.allowed_extensions or [],
                max_file_size=requirement.max_file_size or 10485760,
                is_active=True,
                is_deleted=False,
            )
            definitions_by_code[code] = definition

        ServiceRequiredDocument.objects.filter(pk=requirement.pk).update(
            document_definition_id=definition.pk,
            document_type=definition.code,
            name_ar=definition.name_ar,
            name_en=definition.name_en,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("providers", "0003_providerprofile_organization"),
        ("services", "0007_service_organization_service_scope_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequiredDocumentDefinition",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("delete_reason", models.TextField(blank=True)),
                (
                    "definition_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("code", models.SlugField(max_length=120)),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("allowed_extensions", models.JSONField(blank=True, default=list)),
                ("allowed_mime_types", models.JSONField(blank=True, default=list)),
                ("max_file_size", models.PositiveBigIntegerField(default=10485760)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name_ar"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="serviceproviderassignment",
            name="unique_service_provider_assignment",
        ),
        migrations.RemoveConstraint(
            model_name="servicerelation",
            name="unique_service_relation_per_type",
        ),
        migrations.RemoveConstraint(
            model_name="servicerequireddocument",
            name="unique_service_required_document_type",
        ),
        migrations.AddField(
            model_name="address",
            name="delete_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="address",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="delete_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="delivery_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="delivery_note_ar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="delivery_note_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="delivery_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="delivery_time_mode",
            field=models.CharField(
                choices=[
                    ("duration", "Expected duration"),
                    ("date_range", "Date range"),
                ],
                default="duration",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="public_price_note_ar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="public_price_note_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="show_company_fee_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="show_government_fee_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="show_on_public_site",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="show_total_price_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="delete_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="serviceproviderassignment",
            name="delete_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="serviceproviderassignment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceproviderassignment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="serviceproviderassignment",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="servicerelation",
            name="delete_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="servicerelation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerelation",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicerelation",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="servicerequireddocument",
            name="delete_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="servicerequireddocument",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequireddocument",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicerequireddocument",
            name="instructions_ar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="servicerequireddocument",
            name="instructions_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="servicerequireddocument",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["is_deleted"], name="services_ad_is_dele_39d6b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["show_on_public_site", "is_active"],
                name="services_se_show_on_c207b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_deleted", "is_active"],
                name="services_se_is_dele_4302c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["is_deleted", "is_active"],
                name="services_se_is_dele_5d27d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerelation",
            index=models.Index(
                fields=["is_deleted", "is_active"],
                name="services_se_is_dele_b86cee_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceproviderassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("service", "provider"),
                name="unique_service_provider_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerelation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("source_service", "target_service", "relation_type"),
                name="unique_service_relation_per_type",
            ),
        ),
        migrations.AddField(
            model_name="requireddocumentdefinition",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicerequireddocument",
            name="document_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_links",
                to="services.requireddocumentdefinition",
            ),
        ),
        migrations.RunPython(
            normalize_required_documents,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="servicerequireddocument",
            index=models.Index(
                fields=["service", "is_active"], name="services_se_service_596b4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequireddocument",
            index=models.Index(
                fields=["service", "is_deleted"], name="services_se_service_4120c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequireddocument",
            index=models.Index(
                fields=["document_definition", "is_active"],
                name="services_se_documen_996d9d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequireddocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("service", "document_type"),
                name="unique_service_required_document_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequireddocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("service", "document_definition"),
                name="unique_service_required_document_definition",
            ),
        ),
        migrations.AddIndex(
            model_name="requireddocumentdefinition",
            index=models.Index(
                fields=["code", "is_active"], name="services_re_code_02ecd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requireddocumentdefinition",
            index=models.Index(
                fields=["is_deleted", "is_active"],
                name="services_re_is_dele_ba183d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="requireddocumentdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_deleted", False)),
                fields=("code",),
                name="unique_active_required_document_definition_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="requireddocumentdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_deleted", False)),
                fields=("name_ar",),
                name="unique_active_required_document_definition_name_ar",
            ),
        ),
    ]
