# Generated by Django 5.1.11 on 2026-06-30 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_requireddocumentdefinition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="estimated_duration_max",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="estimated_duration_min",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="delivery_time_mode",
            field=models.CharField(
                choices=[
                    ("duration", "Expected duration"),
                    ("duration_range", "Expected duration range"),
                    ("date_range", "Date range"),
                ],
                default="duration",
                max_length=20,
            ),
        ),
    ]
