# Generated by Django 5.2.13 on 2026-09-05 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0004_providerprofile_delete_reason_and_more"),
        ("services", "0009_service_estimated_duration_max_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceproviderassignment",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_assignments",
                to="providers.providerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="serviceproviderassignment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_assignments",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="servicerelation",
            name="source_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_relations",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="servicerelation",
            name="target_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_relations",
                to="services.service",
            ),
        ),
        migrations.AddConstraint(
            model_name="requireddocumentdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="unique_undeleted_required_document_definition_code",
            ),
        ),
    ]
