from decimal import Decimal

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone

from core.choices import PaymentStatus as SystemPaymentStatus
from orders.models import Order


class Payment(models.Model):
    PaymentStatus = SystemPaymentStatus

    class PaymentMethod(models.TextChoices):
        CASH = "cash", "Cash"
        BANK_TRANSFER = "bank_transfer", "Bank transfer"
        CARD = "card", "Card"
        WALLET = "wallet", "Wallet"
        ONLINE_GATEWAY = "online_gateway", "Online payment gateway"
        OTHER = "other", "Other"

    class PaymentType(models.TextChoices):
        FULL = "full", "Full payment"
        DEPOSIT = "deposit", "Deposit"
        REMAINING_BALANCE = "remaining_balance", "Remaining balance"
        GOVERNMENT_FEE = "government_fee", "Government fee"
        SERVICE_FEE = "service_fee", "Service fee"
        REFUND = "refund", "Refund"

    payment_id = models.BigAutoField(primary_key=True)

    payment_number = models.CharField(
        max_length=30,
        unique=True,
        blank=True,
        editable=False,
        db_index=True,
        help_text="Auto-generated payment number, example: PAY-000001."
    )

    # This creates order_id in the database.
    order = models.ForeignKey(
        Order,
        on_delete=models.PROTECT,
        related_name="payments"
    )
    organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.PROTECT,
        related_name="payments",
        null=True,
        blank=True,
    )

    # User who made the payment.
    # This creates paid_by_id in the database.
    paid_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name="payments_made",
        null=True,
        blank=True
    )

    # Employee/admin who recorded the payment manually, if applicable.
    # This creates recorded_by_id in the database.
    recorded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name="payments_recorded",
        null=True,
        blank=True
    )

    payment_type = models.CharField(
        max_length=30,
        choices=PaymentType.choices,
        default=PaymentType.FULL,
        db_index=True
    )

    method = models.CharField(
        max_length=30,
        choices=PaymentMethod.choices,
        default=PaymentMethod.CASH,
        db_index=True
    )

    status = models.CharField(
        max_length=30,
        choices=PaymentStatus.choices,
        default=PaymentStatus.PENDING,
        db_index=True
    )

    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal("0.00"))]
    )

    currency = models.CharField(
        max_length=3,
        default="JOD",
        help_text="ISO currency code, example: JOD, USD."
    )

    gateway_name = models.CharField(
        max_length=100,
        blank=True,
        help_text="Example: Stripe, PayPal, CliQ, local bank gateway."
    )

    gateway_transaction_id = models.CharField(
        max_length=255,
        blank=True,
        db_index=True,
        help_text="Transaction/reference ID returned by the payment gateway."
    )

    gateway_payment_url = models.URLField(
        blank=True,
        help_text="Payment page URL if generated by an online gateway."
    )

    gateway_response = models.JSONField(
        null=True,
        blank=True,
        help_text="Raw or summarized response from the payment gateway."
    )

    reference_number = models.CharField(
        max_length=120,
        blank=True,
        db_index=True,
        help_text="Manual bank transfer, receipt, cheque, or cash reference number."
    )

    receipt_file = models.FileField(
        upload_to="payments/receipts/",
        blank=True,
        null=True
    )

    failure_reason = models.TextField(blank=True)
    notes = models.TextField(blank=True)

    paid_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the payment was confirmed as paid."
    )

    refunded_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the payment was refunded, if applicable."
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Payment"
        verbose_name_plural = "Payments"
        permissions = [
            ("create_payment_record", "Can create payment records"),
            ("view_payment_status", "Can view payment status"),
            ("refund_payment", "Can refund or adjust payments"),
        ]
        constraints = [
            models.CheckConstraint(
                check=models.Q(amount__gte=0),
                name="payment_amount_gte_0"
            ),
        ]
        indexes = [
            models.Index(fields=["payment_number"]),
            models.Index(fields=["order"]),
            models.Index(fields=["paid_by"]),
            models.Index(fields=["recorded_by"]),
            models.Index(fields=["status"]),
            models.Index(fields=["method"]),
            models.Index(fields=["payment_type"]),
            models.Index(fields=["gateway_transaction_id"]),
            models.Index(fields=["reference_number"]),
            models.Index(fields=["created_at"]),
            models.Index(fields=["status", "created_at"]),
            models.Index(fields=["order", "status"]),
        ]
    def __str__(self):
        if self.payment_number:
            return f"{self.payment_number} - {self.order.order_number}"
        return f"Payment #{self.payment_id}"

    @property
    def id(self):
        return self.pk

    def clean(self):
        errors = {}

        self.currency = (self.currency or "").upper()

        if len(self.currency) != 3:
            errors["currency"] = "Currency must be a 3-letter ISO code."

        if self.status == self.PaymentStatus.PAID and not self.paid_at:
            self.paid_at = timezone.now()

        if self.status in {self.PaymentStatus.REFUNDED, self.PaymentStatus.PARTIALLY_REFUNDED} and not self.refunded_at:
            self.refunded_at = timezone.now()

        if self.status == self.PaymentStatus.FAILED and not self.failure_reason:
            errors["failure_reason"] = "Failed payments require a failure reason."
        if self.order_id and self.organization_id and self.order.organization_id != self.organization_id:
            errors["organization"] = "Payment organization must match the order organization."

        if self.paid_at and self.status not in {
            self.PaymentStatus.PAID,
            self.PaymentStatus.REFUNDED,
            self.PaymentStatus.PARTIALLY_REFUNDED,
        }:
            errors["paid_at"] = "paid_at can only be set for paid/refunded payments."

        if self.refunded_at and self.status not in {
            self.PaymentStatus.REFUNDED,
            self.PaymentStatus.PARTIALLY_REFUNDED,
        }:
            errors["refunded_at"] = "refunded_at can only be set for refunded payments."

        if self.payment_type == self.PaymentType.REFUND and self.status not in {
            self.PaymentStatus.REFUNDED,
            self.PaymentStatus.PARTIALLY_REFUNDED,
            self.PaymentStatus.PENDING,
            self.PaymentStatus.PROCESSING,
        }:
            errors["status"] = "Refund payments must use a refund-related status."

        if errors:
            raise ValidationError(errors)

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        exclude = ["payment_number"] if not self.payment_number else None
        if self.order_id and not self.organization_id:
            self.organization = self.order.organization
        self.full_clean(exclude=exclude)

        super().save(*args, **kwargs)

        if is_new and not self.payment_number:
            self.payment_number = f"PAY-{self.payment_id:06d}"
            super().save(update_fields=["payment_number"])


class Invoice(models.Model):
    class Status(models.TextChoices):
        DRAFT = "draft", "Draft"
        ISSUED = "issued", "Issued"
        PAID = "paid", "Paid"
        PARTIALLY_PAID = "partially_paid", "Partially paid"
        CANCELLED = "cancelled", "Cancelled"

    invoice_id = models.BigAutoField(primary_key=True)
    organization = models.ForeignKey("organizations.Organization", on_delete=models.PROTECT, related_name="invoices")
    order = models.ForeignKey(Order, on_delete=models.PROTECT, related_name="invoices", null=True, blank=True)
    invoice_number = models.CharField(max_length=40, unique=True, blank=True, db_index=True)
    status = models.CharField(max_length=30, choices=Status.choices, default=Status.DRAFT, db_index=True)
    subtotal_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal("0.00"))
    tax_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal("0.00"))
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal("0.00"))
    due_date = models.DateField(null=True, blank=True)
    issued_at = models.DateTimeField(null=True, blank=True)
    paid_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [models.Index(fields=["organization", "status"]), models.Index(fields=["invoice_number"])]

    @property
    def id(self):
        return self.pk

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        self.total_amount = (self.subtotal_amount or Decimal("0.00")) + (self.tax_amount or Decimal("0.00"))
        super().save(*args, **kwargs)
        if is_new and not self.invoice_number:
            self.invoice_number = f"INV-{self.invoice_id:06d}"
            super().save(update_fields=["invoice_number"])


class CommissionRule(models.Model):
    commission_rule_id = models.BigAutoField(primary_key=True)
    organization = models.ForeignKey("organizations.Organization", on_delete=models.CASCADE, related_name="commission_rules")
    service = models.ForeignKey("services.Service", on_delete=models.CASCADE, related_name="commission_rules", null=True, blank=True)
    provider_organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.CASCADE,
        related_name="provider_commission_rules",
        null=True,
        blank=True,
    )
    percentage = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal("0.00"))
    fixed_amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal("0.00"))
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["organization__name", "-is_active", "service__name_ar"]
        indexes = [models.Index(fields=["organization", "is_active"]), models.Index(fields=["provider_organization", "is_active"])]

    @property
    def id(self):
        return self.pk


class ProviderPayout(models.Model):
    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        APPROVED = "approved", "Approved"
        PAID = "paid", "Paid"
        CANCELLED = "cancelled", "Cancelled"

    provider_payout_id = models.BigAutoField(primary_key=True)
    provider_organization = models.ForeignKey("organizations.Organization", on_delete=models.PROTECT, related_name="payouts")
    order = models.ForeignKey(Order, on_delete=models.PROTECT, related_name="provider_payouts")
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal("0.00"))])
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING, db_index=True)
    scheduled_at = models.DateTimeField(null=True, blank=True)
    paid_at = models.DateTimeField(null=True, blank=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [models.Index(fields=["provider_organization", "status"]), models.Index(fields=["order", "status"])]

    @property
    def id(self):
        return self.pk
