# Generated by Django 5.2.13 on 2026-05-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="service_categories",
            field=models.ManyToManyField(
                blank=True, related_name="providers", to="services.servicecategory"
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofile",
            index=models.Index(fields=["city"], name="providers_p_city_8c503d_idx"),
        ),
        migrations.AddIndex(
            model_name="providerprofile",
            index=models.Index(
                fields=["is_available"], name="providers_p_is_avai_c9cb46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofile",
            index=models.Index(
                fields=["is_approved"], name="providers_p_is_appr_70a1b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofile",
            index=models.Index(fields=["rating"], name="providers_p_rating_fc3eaa_idx"),
        ),
    ]
