# Generated by Django 5.2.13 on 2026-05-03 19:54

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("document_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uploaded_by_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("employee", "Employee"),
                            ("provider", "Provider"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        db_index=True,
                        help_text="Example: national_id, passport_copy, payment_receipt, final_report.",
                        max_length=120,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Readable document title.", max_length=255
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=documents.models.secure_document_upload_path
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "stored_filename",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "file_extension",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="Declared or detected MIME type.",
                        max_length=120,
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 checksum for integrity/deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("pending_scan", "Pending security scan"),
                            ("safe", "Safe"),
                            ("unsafe", "Unsafe"),
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=30,
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("not_scanned", "Not scanned"),
                            ("pending", "Pending"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("failed", "Scan failed"),
                        ],
                        db_index=True,
                        default="not_scanned",
                        max_length=30,
                    ),
                ),
                (
                    "scan_engine",
                    models.CharField(
                        blank=True,
                        help_text="Example: ClamAV, external_scan_service.",
                        max_length=100,
                    ),
                ),
                (
                    "scan_result",
                    models.JSONField(
                        blank=True, help_text="Security scan result details.", null=True
                    ),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_final_document",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_note", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. Do not physically delete important documents.",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
