# Generated by Django 5.2.13 on 2026-05-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_document_file_size_gte_0"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("verify_document", "Can verify documents"),
                    ("upload_final_document", "Can upload final documents"),
                ],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
    ]
