# Generated by Django 5.2.13 on 2026-05-12 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_document_auto_approved_by_rule"),
        ("orders", "0009_add_order_deleted_status_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["order", "is_deleted", "status"],
                name="doc_order_deleted_status_idx",
            ),
        ),
    ]
