# Generated by Django 5.2.13 on 2026-05-10 18:41

import django.core.validators
import django.utils.timezone
import public_site.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advertisement_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=255,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        validators=[public_site.validators.validate_no_script_content]
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "advertisement_type",
                    models.CharField(
                        choices=[
                            ("new_service", "New service"),
                            ("office_announcement", "Office announcement"),
                            ("offer", "Offer"),
                            ("important_alert", "Important alert"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="public_site/advertisements/",
                        validators=[public_site.validators.PublicSiteImageValidator()],
                    ),
                ),
                (
                    "button_text_ar",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "button_text_en",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        validators=[public_site.validators.validate_safe_url],
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color such as #0b67b2.",
                                regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color such as #0b67b2.",
                                regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "ordering": ["display_order", "-start_date", "-advertisement_id"],
                "indexes": [
                    models.Index(
                        fields=["advertisement_type", "is_active"],
                        name="public_site_adverti_95b918_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="public_site_start_d_3bf83a_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="public_site_ad_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicPageContent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "version_name",
                    models.CharField(
                        default="Default Homepage",
                        max_length=120,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "hero_title_ar",
                    models.CharField(
                        max_length=255,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "hero_title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "hero_subtitle_ar",
                    models.TextField(
                        validators=[public_site.validators.validate_no_script_content]
                    ),
                ),
                (
                    "hero_subtitle_en",
                    models.TextField(
                        blank=True,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "primary_button_text",
                    models.CharField(
                        max_length=120,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "primary_button_url",
                    models.CharField(
                        max_length=500,
                        validators=[public_site.validators.validate_safe_url],
                    ),
                ),
                (
                    "secondary_button_text",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "secondary_button_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        validators=[public_site.validators.validate_safe_url],
                    ),
                ),
                (
                    "hero_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="public_site/homepage/hero/",
                        validators=[public_site.validators.PublicSiteImageValidator()],
                    ),
                ),
                (
                    "how_it_works_text",
                    models.TextField(
                        validators=[public_site.validators.validate_no_script_content]
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=30,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        max_length=30,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "office_address",
                    models.CharField(
                        max_length=255,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        validators=[public_site.validators.validate_no_script_content]
                    ),
                ),
                ("active_content", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Public page content",
                "verbose_name_plural": "Public page contents",
                "ordering": ["-active_content", "-updated_at", "-content_id"],
                "indexes": [
                    models.Index(
                        fields=["active_content"], name="public_site_active__a6d203_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="public_site_updated_e2f167_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active_content", True)),
                        fields=("active_content",),
                        name="unique_active_public_page_content",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SiteTheme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("theme_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        default="Default Theme",
                        max_length=120,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color such as #0b67b2.",
                                regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color such as #0b67b2.",
                                regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color such as #0b67b2.",
                                regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color such as #0b67b2.",
                                regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "header_background_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color such as #0b67b2.",
                                regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "footer_background_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color such as #0b67b2.",
                                regex="^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="public_site/themes/logos/",
                        validators=[public_site.validators.PublicSiteImageValidator()],
                    ),
                ),
                (
                    "favicon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="public_site/themes/favicons/",
                        validators=[
                            public_site.validators.PublicSiteImageValidator(
                                allow_favicon_types=True
                            )
                        ],
                    ),
                ),
                ("active_theme", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Site theme",
                "verbose_name_plural": "Site themes",
                "ordering": ["-active_theme", "name", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["active_theme"], name="public_site_active__3cf8b5_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="public_site_updated_552c21_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active_theme", True)),
                        fields=("active_theme",),
                        name="unique_active_public_site_theme",
                    )
                ],
            },
        ),
    ]
