# Generated by Django 5.2.13 on 2026-05-16 09:48

import django.db.models.deletion
import public_site.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0001_initial"),
        ("services", "0004_servicerequireddocument_rule_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MissingServiceRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "request_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated missing service request number, example: MSR-000001.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("homepage_chat", "Homepage chat"),
                            ("contact_page", "Contact page"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="homepage_chat",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_review", "In review"),
                            ("service_exists", "Service exists"),
                            ("forwarded", "Forwarded"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=30,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        max_length=255,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "request_message",
                    models.TextField(
                        validators=[public_site.validators.validate_no_script_content]
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "requester_phone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                ("requester_email", models.EmailField(blank=True, max_length=254)),
                (
                    "preferred_contact_channel",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_missing_service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_missing_service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missing_service_requests",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Missing service request",
                "verbose_name_plural": "Missing service requests",
                "ordering": ["-created_at", "-request_id"],
                "indexes": [
                    models.Index(
                        fields=["request_number"], name="public_site_request_ecbd7d_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="public_site_status_169378_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="public_site_assigne_7f55a0_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="public_site_source_da97f0_idx",
                    ),
                ],
            },
        ),
    ]
