# Generated by Django 5.2.13 on 2026-05-17 08:52

import public_site.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0002_missingservicerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicpagecontent",
            name="footer_text_en",
            field=models.TextField(
                blank=True,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
        migrations.AddField(
            model_name="publicpagecontent",
            name="how_it_works_text_en",
            field=models.TextField(
                blank=True,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
        migrations.AddField(
            model_name="publicpagecontent",
            name="office_address_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
        migrations.AddField(
            model_name="publicpagecontent",
            name="primary_button_text_en",
            field=models.CharField(
                blank=True,
                max_length=120,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
        migrations.AddField(
            model_name="publicpagecontent",
            name="secondary_button_text_en",
            field=models.CharField(
                blank=True,
                max_length=120,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
    ]
