# Generated by Django 5.1.11 on 2026-10-03 16:19

import public_site.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "public_site",
            "0004_advertisement_delete_reason_advertisement_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inquiry_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=30,
                        validators=[public_site.validators.validate_no_script_content],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "message",
                    models.TextField(
                        validators=[public_site.validators.validate_no_script_content]
                    ),
                ),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
