# Generated by Django 5.1.11 on 2026-10-03 16:22

import django.core.validators
import public_site.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0005_contactinquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicpagecontent",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
        migrations.AlterField(
            model_name="publicpagecontent",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="publicpagecontent",
            name="office_address",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
        migrations.AlterField(
            model_name="publicpagecontent",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
    ]
