# Generated by Django 5.1.11 on 2026-10-04 05:42

import public_site.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_site", "0006_alter_publicpagecontent_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicpagecontent",
            name="privacy_policy_ar",
            field=models.TextField(
                blank=True,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
        migrations.AddField(
            model_name="publicpagecontent",
            name="privacy_policy_en",
            field=models.TextField(
                blank=True,
                validators=[public_site.validators.validate_no_script_content],
            ),
        ),
    ]
