export const mockCategories = [
  { id: 1, name_ar: 'الجوازات والأحوال المدنية', name_en: 'Civil Status', slug: 'civil-status', description_ar: 'خدمات الأحوال المدنية والجوازات الأكثر طلباً.', service_count: 2 },
  { id: 2, name_ar: 'الضمان الاجتماعي', name_en: 'Social Security', slug: 'social-security', description_ar: 'طلبات المؤسسة العامة للضمان.', service_count: 0 },
  { id: 3, name_ar: 'الضريبة', name_en: 'Tax', slug: 'tax', description_ar: 'براءات الذمة والملفات الضريبية.', service_count: 1 },
  { id: 4, name_ar: 'وزارة العمل', name_en: 'Labour', slug: 'labour', description_ar: 'تصاريح وإجراءات وزارة العمل.', service_count: 0 },
  { id: 5, name_ar: 'رخص المهن والمسقفات', name_en: 'Licenses', slug: 'licenses', description_ar: 'الرخص المهنية ورسوم المسقفات.', service_count: 0 },
  { id: 6, name_ar: 'العقار والمساحة', name_en: 'Property', slug: 'property', description_ar: 'خدمات الأراضي والمساحة والعقار.', service_count: 0 },
  { id: 7, name_ar: 'خدمات عامة سريعة', name_en: 'General Services', slug: 'general', description_ar: 'خدمات متفرقة سريعة التنفيذ.', service_count: 0 },
]

export const mockRequiredDocumentDefinitions = [
  {
    id: 1,
    code: 'national_id',
    name_ar: 'هوية شخصية',
    name_en: 'National ID',
    description_ar: 'نسخة واضحة من الهوية الشخصية.',
    allowed_extensions: ['.pdf', '.jpg', '.png'],
    max_file_size: 10485760,
    sort_order: 1,
    is_active: true,
  },
  {
    id: 2,
    code: 'authorization_letter',
    name_ar: 'تفويض',
    name_en: 'Authorization Letter',
    description_ar: 'تفويض موقع عند الحاجة.',
    allowed_extensions: ['.pdf', '.jpg'],
    max_file_size: 10485760,
    sort_order: 2,
    is_active: true,
  },
  {
    id: 3,
    code: 'proof_of_address',
    name_ar: 'إثبات سكن',
    name_en: 'Proof of Address',
    description_ar: 'وثيقة تثبت عنوان السكن الحالي.',
    allowed_extensions: ['.pdf', '.jpg'],
    max_file_size: 10485760,
    sort_order: 3,
    is_active: true,
  },
]

export const mockServices = [
  {
    id: 1,
    category: mockCategories[0],
    name_ar: 'شهادة عدم محكومية',
    name_en: 'No Criminal Record',
    slug: 'no-criminal-record',
    description_ar: 'إصدار شهادة عدم محكومية مع متابعة كاملة للطلب.',
    required_documents: [
      { id: 1, definition_id: 1, document_type: 'national_id', name_ar: 'هوية شخصية', allowed_extensions: ['.pdf', '.jpg'], max_file_size: 10485760 },
      { id: 2, definition_id: 2, document_type: 'authorization_letter', name_ar: 'تفويض إن وجد', allowed_extensions: ['.pdf', '.jpg'], max_file_size: 10485760, is_required: false },
    ],
    estimated_duration: 2,
    service_fee: 12,
    government_fee: 5,
    total_fee: 17,
    pricing: {
      total_price: 17,
      government_fee: 5,
      company_fee: 12,
      public_note_ar: '',
      public_note_en: '',
    },
    delivery_time: {
      mode: 'duration',
      label: 'Expected completion: 2 days',
      label_ar: 'المدة المتوقعة: 2 يوم',
      label_en: 'Expected completion: 2 days',
      expected_duration: 2,
      expected_duration_unit: 'days',
      start_date: null,
      end_date: null,
    },
    is_featured: true,
  },
  {
    id: 2,
    category: mockCategories[0],
    name_ar: 'تجديد جواز سفر',
    name_en: 'Passport Renewal',
    slug: 'passport-renewal',
    description_ar: 'تجهيز الطلب وتدقيق الوثائق ومتابعة التجديد حتى صدور النتيجة.',
    required_documents: [
      { id: 3, definition_id: 3, document_type: 'proof_of_address', name_ar: 'إثبات سكن', allowed_extensions: ['.pdf', '.jpg'], max_file_size: 10485760 },
      { id: 4, definition_id: 1, document_type: 'national_id', name_ar: 'الهوية الشخصية', allowed_extensions: ['.pdf', '.jpg'], max_file_size: 10485760 },
    ],
    estimated_duration: 5,
    service_fee: 18,
    government_fee: 10,
    total_fee: 28,
    pricing: {
      total_price: 28,
      government_fee: null,
      company_fee: null,
      public_note_ar: 'يتم تأكيد الرسوم الحكومية بعد المراجعة.',
      public_note_en: 'Government fees are confirmed after review.',
    },
    delivery_time: {
      mode: 'date_range',
      label: 'From 2026-07-01 to 2026-09-30',
      label_ar: 'من 2026-07-01 إلى 2026-09-30',
      label_en: 'From 2026-07-01 to 2026-09-30',
      start_date: '2026-07-01',
      end_date: '2026-09-30',
      expected_duration: null,
      expected_duration_unit: null,
    },
    is_featured: true,
  },
  {
    id: 3,
    category: mockCategories[2],
    name_ar: 'براءة ذمة ضريبية',
    name_en: 'Tax Clearance',
    slug: 'tax-clearance',
    description_ar: 'متابعة طلب براءة الذمة الضريبية للشركات والأفراد.',
    required_documents: [{ id: 5, document_type: 'tax_number', name_ar: 'رقم ضريبي', allowed_extensions: ['.pdf'], max_file_size: 10485760 }],
    estimated_duration: 3,
    service_fee: 14,
    government_fee: 7,
    total_fee: 21,
    pricing: {
      total_price: 21,
      government_fee: 7,
      company_fee: 14,
      public_note_ar: '',
      public_note_en: '',
    },
    delivery_time: {
      mode: 'duration',
      label: 'Expected completion: 3 days',
      label_ar: 'المدة المتوقعة: 3 يوم',
      label_en: 'Expected completion: 3 days',
      expected_duration: 3,
      expected_duration_unit: 'days',
      start_date: null,
      end_date: null,
    },
    is_featured: false,
  },
]

export const mockOrders = [
  {
    id: 1,
    order_number: 'KH-2026-000001',
    service: mockServices[0],
    customer: {
      id: 1,
      full_name: 'أحمد خالد',
      phone: '0790000002',
      email: 'customer@khalisni.local',
      national_id: '9876543210',
    },
    city: 'عمّان',
    status: 'IN_PROGRESS',
    priority: 'NORMAL',
    expected_delivery_date: '2026-04-28',
    final_price: 17,
    customer_notes: 'أحتاج النتيجة بأسرع وقت',
    internal_notes: 'الملف مكتمل',
    documents: [
      {
        id: 11,
        document_type: 'هوية',
        original_filename: 'id-card.pdf',
        download_url: '#',
        is_final_document: false,
      },
    ],
    status_logs: [
      { id: 1, new_status: 'NEW', note: 'تم إنشاء الطلب', created_at: '2026-04-24T10:00:00Z' },
      { id: 2, new_status: 'UNDER_REVIEW', note: 'تدقيق الوثائق', created_at: '2026-04-24T11:00:00Z' },
      { id: 3, new_status: 'ASSIGNED', note: 'تم تعيين مزود الخدمة', created_at: '2026-04-24T12:00:00Z' },
      { id: 4, new_status: 'IN_PROGRESS', note: 'قيد التنفيذ', created_at: '2026-04-24T13:00:00Z' },
    ],
    notes: [{ id: 1, note: 'تم استلام جميع الوثائق المطلوبة.', visibility: 'CUSTOMER', created_at: '2026-04-24T11:00:00Z' }],
    assigned_provider: {
      id: 1,
      full_name: 'محمود علي',
      provider_type: 'Government Services Specialist',
      city: 'عمّان',
      rating: 4.8,
      is_available: true,
    },
    rating: null,
    allowed_actions: {
      can_view: true,
      available_status_transitions: ['WAITING_GOVERNMENT'],
      can_cancel: false,
      can_upload_customer_document: false,
      can_view_missing_documents_form: false,
      can_submit_rating: false,
      can_request_documents: false,
      can_assign_provider: false,
      can_add_internal_note: true,
      can_add_customer_note: false,
      can_verify_documents: false,
      can_reject: false,
      can_complete: false,
      can_upload_final_document: true,
    },
  },
  {
    id: 2,
    order_number: 'KH-2026-000002',
    service: mockServices[1],
    customer: {
      id: 1,
      full_name: 'أحمد خالد',
      phone: '0790000002',
      email: 'customer@khalisni.local',
      national_id: '9876543210',
    },
    city: 'الزرقاء',
    status: 'COMPLETED',
    priority: 'HIGH',
    expected_delivery_date: '2026-04-22',
    final_price: 28,
    customer_notes: '',
    internal_notes: 'تم الإغلاق',
    documents: [
      {
        id: 21,
        document_type: 'Final Result',
        original_filename: 'passport-renewal-result.pdf',
        download_url: '#',
        is_final_document: true,
      },
    ],
    status_logs: [
      { id: 5, new_status: 'NEW', note: 'تم الإنشاء', created_at: '2026-04-20T09:00:00Z' },
      { id: 6, new_status: 'COMPLETED', note: 'تم التسليم', created_at: '2026-04-22T16:30:00Z' },
    ],
    notes: [{ id: 3, note: 'الوثيقة النهائية أصبحت متاحة للتحميل.', visibility: 'CUSTOMER', created_at: '2026-04-22T16:00:00Z' }],
    assigned_provider: {
      id: 1,
      full_name: 'محمود علي',
      provider_type: 'Government Services Specialist',
      city: 'عمّان',
      rating: 4.8,
      is_available: true,
    },
    rating: { id: 1, score: 5, comment: 'خدمة ممتازة', created_at: '2026-04-22T17:00:00Z' },
    allowed_actions: {
      can_view: true,
      available_status_transitions: [],
      can_cancel: false,
      can_upload_customer_document: false,
      can_view_missing_documents_form: false,
      can_submit_rating: false,
      can_request_documents: false,
      can_assign_provider: false,
      can_add_internal_note: false,
      can_add_customer_note: false,
      can_verify_documents: false,
      can_reject: false,
      can_complete: false,
      can_upload_final_document: false,
    },
  },
]

export const mockAdminDashboard = {
  cards: {
    new_orders_today: 8,
    orders_in_progress: 14,
    waiting_customer: 5,
    completed_this_week: 19,
    delayed_orders: 3,
    revenue_estimate: 640,
  },
  orders_by_status: [
    { status: 'NEW', total: 8 },
    { status: 'IN_PROGRESS', total: 14 },
    { status: 'WAITING_CUSTOMER', total: 5 },
    { status: 'COMPLETED', total: 19 },
  ],
  top_services: [
    { service__name_ar: 'شهادة عدم محكومية', total: 22 },
    { service__name_ar: 'تجديد جواز سفر', total: 15 },
    { service__name_ar: 'براءة ذمة ضريبية', total: 11 },
  ],
  provider_performance: [
    { assigned_provider__user__full_name: 'محمود علي', total: 14 },
    { assigned_provider__user__full_name: 'رهف سمير', total: 9 },
  ],
}

export const mockProviders = [
  {
    id: 1,
    full_name: 'محمود علي',
    email: 'provider@khalisni.local',
    phone: '0790000003',
    provider_type: 'Government Services Specialist',
    service_categories: ['الجوازات والأحوال المدنية', 'الضريبة'],
    city: 'عمّان',
    rating: 4.8,
    total_completed_orders: 44,
    is_available: true,
  },
]

export const mockNotifications = [
  { id: 1, title: 'تم استلام الطلب', status: 'SENT', user_name: 'أحمد خالد', order_number: 'KH-2026-000001', created_at: '2026-04-24T10:00:00Z' },
  { id: 2, title: 'مطلوب وثائق إضافية', status: 'FAILED', user_name: 'ليلى أحمد', order_number: 'KH-2026-000004', created_at: '2026-04-24T14:00:00Z' },
]

export const mockMissingServiceRequests = [
  {
    id: 1,
    request_number: 'MSR-000001',
    service_name: 'معاملة تصديق جامعية',
    request_message: 'أحتاج خدمة تصديق أوراق جامعية من جهة حكومية وغير موجودة حالياً.',
    requester_name: 'سارة محمود',
    requester_phone: '0791111111',
    requester_email: 'sara@example.com',
    preferred_contact_channel: 'whatsapp',
    source: 'homepage_chat',
    status: 'new',
    assigned_to: 3,
    assigned_to_name: 'ليلى أحمد',
    matched_service: null,
    matched_service_name: '',
    response_message: '',
    internal_notes: 'بانتظار مراجعة تفاصيل الجهة المطلوبة.',
    created_at: '2026-05-15T09:15:00Z',
    updated_at: '2026-05-15T09:15:00Z',
    resolved_at: null,
  },
  {
    id: 2,
    request_number: 'MSR-000002',
    service_name: 'تجديد جواز سفر',
    request_message: 'المستخدم لم يجد خدمة تجديد جواز السفر في الصفحة الرئيسية.',
    requester_name: 'محمد العلي',
    requester_phone: '0792222222',
    requester_email: '',
    preferred_contact_channel: 'phone',
    source: 'homepage_chat',
    status: 'service_exists',
    assigned_to: 1,
    assigned_to_name: 'مشرف النظام',
    matched_service: 2,
    matched_service_name: 'تجديد جواز سفر',
    response_message: 'تم توجيه العميل إلى الخدمة الموجودة داخل التطبيق.',
    internal_notes: 'لا حاجة لإنشاء خدمة جديدة.',
    created_at: '2026-05-14T12:30:00Z',
    updated_at: '2026-05-14T14:00:00Z',
    resolved_at: '2026-05-14T14:00:00Z',
  },
]

export const mockAuditLogs = [
  { id: 1, user_name: 'Khalisni Admin', action: 'assign_provider', entity_type: 'Order', entity_id: '1', ip_address: '127.0.0.1', created_at: '2026-04-24T12:00:00Z' },
  { id: 2, user_name: 'Khalisni Admin', action: 'complete_order', entity_type: 'Order', entity_id: '2', ip_address: '127.0.0.1', created_at: '2026-04-24T16:30:00Z' },
]

