export const mockCategories = [
  { id: 1, name_ar: 'الجوازات والأحوال المدنية', slug: 'civil-status' },
  { id: 2, name_ar: 'الضمان الاجتماعي', slug: 'social-security' },
  { id: 3, name_ar: 'الضريبة', slug: 'tax' },
  { id: 4, name_ar: 'وزارة العمل', slug: 'labour' },
  { id: 5, name_ar: 'رخص المهن والمسقفات', slug: 'licenses' },
  { id: 6, name_ar: 'العقار والمساحة', slug: 'property' },
  { id: 7, name_ar: 'خدمات عامة سريعة', slug: 'general' },
]

export const mockServices = [
  {
    id: 1,
    category: mockCategories[0],
    name_ar: 'شهادة عدم محكومية',
    name_en: 'No Criminal Record',
    slug: 'no-criminal-record',
    description_ar: 'إصدار شهادة عدم محكومية مع متابعة كاملة للطلب.',
    required_documents: ['هوية شخصية', 'تفويض إن وجد'],
    estimated_duration: 2,
    service_fee: 12,
    government_fee: 5,
    total_fee: 17,
    is_featured: true,
  },
  {
    id: 2,
    category: mockCategories[0],
    name_ar: 'تجديد جواز سفر',
    name_en: 'Passport Renewal',
    slug: 'passport-renewal',
    description_ar: 'تجهيز الطلب وتدقيق الوثائق ومتابعة التجديد حتى صدور النتيجة.',
    required_documents: ['الجواز الحالي', 'صورة شخصية', 'إثبات سكن'],
    estimated_duration: 5,
    service_fee: 18,
    government_fee: 10,
    total_fee: 28,
    is_featured: true,
  },
  {
    id: 3,
    category: mockCategories[2],
    name_ar: 'براءة ذمة ضريبية',
    name_en: 'Tax Clearance',
    slug: 'tax-clearance',
    description_ar: 'متابعة طلب براءة الذمة الضريبية للشركات والأفراد.',
    required_documents: ['رقم ضريبي', 'هوية أو سجل تجاري'],
    estimated_duration: 3,
    service_fee: 14,
    government_fee: 7,
    total_fee: 21,
    is_featured: false,
  },
]

export const mockOrders = [
  {
    id: 1,
    order_number: 'KH-2026-000001',
    service: mockServices[0],
    customer: {
      id: 1,
      full_name: 'أحمد خالد',
      phone: '0790000002',
      email: 'customer@khalisni.local',
      national_id: '9876543210',
    },
    city: 'عمّان',
    status: 'IN_PROGRESS',
    priority: 'NORMAL',
    expected_delivery_date: '2026-04-28',
    final_price: 17,
    customer_notes: 'أحتاج النتيجة بأسرع وقت',
    internal_notes: 'الملف مكتمل',
    documents: [
      {
        id: 11,
        document_type: 'هوية',
        original_filename: 'id-card.pdf',
        download_url: '#',
        is_final_document: false,
      },
    ],
    status_logs: [
      { id: 1, new_status: 'NEW', note: 'تم إنشاء الطلب', created_at: '2026-04-24T10:00:00Z' },
      { id: 2, new_status: 'UNDER_REVIEW', note: 'تدقيق الوثائق', created_at: '2026-04-24T11:00:00Z' },
      { id: 3, new_status: 'ASSIGNED', note: 'تم تعيين مزود الخدمة', created_at: '2026-04-24T12:00:00Z' },
      { id: 4, new_status: 'IN_PROGRESS', note: 'قيد التنفيذ', created_at: '2026-04-24T13:00:00Z' },
    ],
    notes: [{ id: 1, note: 'تم استلام جميع الوثائق المطلوبة.', visibility: 'CUSTOMER', created_at: '2026-04-24T11:00:00Z' }],
    assigned_provider: {
      id: 1,
      full_name: 'محمود علي',
      provider_type: 'Government Services Specialist',
      city: 'عمّان',
      rating: 4.8,
      is_available: true,
    },
    rating: null,
    allowed_actions: {
      can_view: true,
      available_status_transitions: ['WAITING_GOVERNMENT'],
      can_cancel: false,
      can_upload_customer_document: false,
      can_view_missing_documents_form: false,
      can_submit_rating: false,
      can_request_documents: false,
      can_assign_provider: false,
      can_add_internal_note: true,
      can_add_customer_note: false,
      can_verify_documents: false,
      can_reject: false,
      can_complete: false,
      can_upload_final_document: true,
    },
  },
  {
    id: 2,
    order_number: 'KH-2026-000002',
    service: mockServices[1],
    customer: {
      id: 1,
      full_name: 'أحمد خالد',
      phone: '0790000002',
      email: 'customer@khalisni.local',
      national_id: '9876543210',
    },
    city: 'الزرقاء',
    status: 'COMPLETED',
    priority: 'HIGH',
    expected_delivery_date: '2026-04-22',
    final_price: 28,
    customer_notes: '',
    internal_notes: 'تم الإغلاق',
    documents: [
      {
        id: 21,
        document_type: 'Final Result',
        original_filename: 'passport-renewal-result.pdf',
        download_url: '#',
        is_final_document: true,
      },
    ],
    status_logs: [
      { id: 5, new_status: 'NEW', note: 'تم الإنشاء', created_at: '2026-04-20T09:00:00Z' },
      { id: 6, new_status: 'COMPLETED', note: 'تم التسليم', created_at: '2026-04-22T16:30:00Z' },
    ],
    notes: [{ id: 3, note: 'الوثيقة النهائية أصبحت متاحة للتحميل.', visibility: 'CUSTOMER', created_at: '2026-04-22T16:00:00Z' }],
    assigned_provider: {
      id: 1,
      full_name: 'محمود علي',
      provider_type: 'Government Services Specialist',
      city: 'عمّان',
      rating: 4.8,
      is_available: true,
    },
    rating: { id: 1, score: 5, comment: 'خدمة ممتازة', created_at: '2026-04-22T17:00:00Z' },
    allowed_actions: {
      can_view: true,
      available_status_transitions: [],
      can_cancel: false,
      can_upload_customer_document: false,
      can_view_missing_documents_form: false,
      can_submit_rating: false,
      can_request_documents: false,
      can_assign_provider: false,
      can_add_internal_note: false,
      can_add_customer_note: false,
      can_verify_documents: false,
      can_reject: false,
      can_complete: false,
      can_upload_final_document: false,
    },
  },
]

export const mockAdminDashboard = {
  cards: {
    new_orders_today: 8,
    orders_in_progress: 14,
    waiting_customer: 5,
    completed_this_week: 19,
    delayed_orders: 3,
    revenue_estimate: 640,
  },
  orders_by_status: [
    { status: 'NEW', total: 8 },
    { status: 'IN_PROGRESS', total: 14 },
    { status: 'WAITING_CUSTOMER', total: 5 },
    { status: 'COMPLETED', total: 19 },
  ],
  top_services: [
    { service__name_ar: 'شهادة عدم محكومية', total: 22 },
    { service__name_ar: 'تجديد جواز سفر', total: 15 },
    { service__name_ar: 'براءة ذمة ضريبية', total: 11 },
  ],
  provider_performance: [
    { assigned_provider__user__full_name: 'محمود علي', total: 14 },
    { assigned_provider__user__full_name: 'رهف سمير', total: 9 },
  ],
}

export const mockProviders = [
  {
    id: 1,
    full_name: 'محمود علي',
    email: 'provider@khalisni.local',
    phone: '0790000003',
    provider_type: 'Government Services Specialist',
    service_categories: ['الجوازات والأحوال المدنية', 'الضريبة'],
    city: 'عمّان',
    rating: 4.8,
    total_completed_orders: 44,
    is_available: true,
  },
]

export const mockNotifications = [
  { id: 1, title: 'تم استلام الطلب', status: 'SENT', user_name: 'أحمد خالد', order_number: 'KH-2026-000001', created_at: '2026-04-24T10:00:00Z' },
  { id: 2, title: 'مطلوب وثائق إضافية', status: 'FAILED', user_name: 'ليلى أحمد', order_number: 'KH-2026-000004', created_at: '2026-04-24T14:00:00Z' },
]

export const mockAuditLogs = [
  { id: 1, user_name: 'Khalisni Admin', action: 'assign_provider', entity_type: 'Order', entity_id: '1', ip_address: '127.0.0.1', created_at: '2026-04-24T12:00:00Z' },
  { id: 2, user_name: 'Khalisni Admin', action: 'complete_order', entity_type: 'Order', entity_id: '2', ip_address: '127.0.0.1', created_at: '2026-04-24T16:30:00Z' },
]

