# Generated by Django 5.2.13 on 2026-05-03 19:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "payment_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated payment number, example: PAY-000001.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("full", "Full payment"),
                            ("deposit", "Deposit"),
                            ("remaining_balance", "Remaining balance"),
                            ("government_fee", "Government fee"),
                            ("service_fee", "Service fee"),
                            ("refund", "Refund"),
                        ],
                        db_index=True,
                        default="full",
                        max_length=30,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank transfer"),
                            ("card", "Card"),
                            ("wallet", "Wallet"),
                            ("online_gateway", "Online payment gateway"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="cash",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="JOD",
                        help_text="ISO currency code, example: JOD, USD.",
                        max_length=3,
                    ),
                ),
                (
                    "gateway_name",
                    models.CharField(
                        blank=True,
                        help_text="Example: Stripe, PayPal, CliQ, local bank gateway.",
                        max_length=100,
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Transaction/reference ID returned by the payment gateway.",
                        max_length=255,
                    ),
                ),
                (
                    "gateway_payment_url",
                    models.URLField(
                        blank=True,
                        help_text="Payment page URL if generated by an online gateway.",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        help_text="Raw or summarized response from the payment gateway.",
                        null=True,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Manual bank transfer, receipt, cheque, or cash reference number.",
                        max_length=120,
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True, null=True, upload_to="payments/receipts/"
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the payment was confirmed as paid.",
                        null=True,
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the payment was refunded, if applicable.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_number"], name="payment_pay_payment_67e9d9_idx"
                    ),
                    models.Index(
                        fields=["order"], name="payment_pay_order_i_211f02_idx"
                    ),
                    models.Index(
                        fields=["paid_by"], name="payment_pay_paid_by_dba0ea_idx"
                    ),
                    models.Index(
                        fields=["recorded_by"], name="payment_pay_recorde_a74d1d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="payment_pay_status_124d3d_idx"
                    ),
                    models.Index(
                        fields=["method"], name="payment_pay_method_521bbf_idx"
                    ),
                    models.Index(
                        fields=["payment_type"], name="payment_pay_payment_9475fb_idx"
                    ),
                    models.Index(
                        fields=["gateway_transaction_id"],
                        name="payment_pay_gateway_eb35a7_idx",
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="payment_pay_referen_97c73a_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="payment_pay_created_671024_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="payment_pay_status_19fbf4_idx",
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="payment_pay_order_i_b37863_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="payment_amount_gte_0",
                    )
                ],
            },
        ),
    ]
