# Generated by Django 5.2.13 on 2026-05-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("create_payment_record", "Can create payment records"),
                    ("view_payment_status", "Can view payment status"),
                    ("refund_payment", "Can refund or adjust payments"),
                ],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
