# Generated by Django 5.2.13 on 2026-05-16 18:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_payment_organization(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")
    for payment in Payment.objects.select_related("order", "order__organization").all():
        if payment.organization_id is None and getattr(payment.order, "organization_id", None):
            payment.organization_id = payment.order.organization_id
            payment.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_assigned_provider_organization_order_branch_and_more"),
        ("organizations", "0001_initial"),
        ("payment", "0002_alter_payment_options"),
        ("services", "0007_service_organization_service_scope_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="organizations.organization",
            ),
        ),
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "commission_rule_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="organizations.organization",
                    ),
                ),
                (
                    "provider_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_commission_rules",
                        to="organizations.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name", "-is_active", "service__name_ar"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="payment_com_organiz_7f61dd_idx",
                    ),
                    models.Index(
                        fields=["provider_organization", "is_active"],
                        name="payment_com_provide_77b3f4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("invoice_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="orders.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="payment_inv_organiz_7669bf_idx",
                    ),
                    models.Index(
                        fields=["invoice_number"], name="payment_inv_invoice_b50744_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderPayout",
            fields=[
                (
                    "provider_payout_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_payouts",
                        to="orders.order",
                    ),
                ),
                (
                    "provider_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider_organization", "status"],
                        name="payment_pro_provide_8b5766_idx",
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="payment_pro_order_i_2bc9f5_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_payment_organization,
            migrations.RunPython.noop,
        ),
    ]
