# Generated by Django 5.2.13 on 2026-05-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("audit_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("restore", "Restore"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("status_change", "Status change"),
                            ("assign", "Assign"),
                            ("unassign", "Unassign"),
                            ("upload_document", "Upload document"),
                            ("delete_document", "Delete document"),
                            ("payment_update", "Payment update"),
                            ("comment", "Comment"),
                            ("notification_sent", "Notification sent"),
                            ("system_event", "System event"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("client_portal", "Client portal"),
                            ("employee_portal", "Employee portal"),
                            ("provider_portal", "Provider portal"),
                            ("api", "API"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        db_index=True,
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Example: Order, Service, Payment, User",
                        max_length=120,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True,
                        help_text="Primary key of the affected record.",
                        max_length=120,
                    ),
                ),
                (
                    "entity_name",
                    models.CharField(
                        blank=True,
                        help_text="Readable reference, example: ORD-000001 or SRV-000001.",
                        max_length=255,
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="Field values before the change.",
                        null=True,
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="Field values after the change.",
                        null=True,
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of fields changed by this action.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Human-readable audit message."
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Used when status is failed."
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Used to group logs from the same HTTP request or process.",
                        max_length=100,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log",
                "verbose_name_plural": "Audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_audit_user_id_a3c2bc_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_audit_action_766c6d_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["request_id"], name="audit_audit_request_06fe30_idx"
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="audit_audit_source_a7b9b7_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="audit_audit_status_919dd5_idx",
                    ),
                ],
            },
        ),
    ]
