# Generated by Django 5.2.13 on 2026-05-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditlog_user_role"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_user_ro_531f85_idx",
            old_name="audit_audit_user_ro_845dd3_idx",
        ),
    ]
