# Generated by Django 5.2.13 on 2026-06-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "audit",
            "0004_rename_audit_audit_user_ro_845dd3_idx_audit_audit_user_ro_531f85_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("restore", "Restore"),
                    ("register", "Register"),
                    ("update_profile", "Update profile"),
                    ("create_order", "Create order"),
                    ("customer_upload_document", "Customer upload document"),
                    ("rate_order", "Rate order"),
                    ("change_order_status", "Change order status"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("password_reset_request", "Password reset request"),
                    ("password_reset_success", "Password reset success"),
                    ("status_change", "Status change"),
                    ("assign", "Assign"),
                    ("unassign", "Unassign"),
                    ("assign_provider", "Assign provider"),
                    ("request_documents", "Request documents"),
                    ("add_note", "Add note"),
                    ("complete_order", "Complete order"),
                    ("reject_order", "Reject order"),
                    ("provider_status_update", "Provider status update"),
                    ("provider_add_note", "Provider add note"),
                    ("upload_document", "Upload document"),
                    ("upload_final_document", "Upload final document"),
                    (
                        "provider_upload_final_document",
                        "Provider upload final document",
                    ),
                    ("delete_document", "Delete document"),
                    ("payment_update", "Payment update"),
                    ("comment", "Comment"),
                    ("notification_sent", "Notification sent"),
                    ("system_event", "System event"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
